// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: croupier/agent/v1/register.proto

package agentv1

import (
	v1 "github.com/cuihairu/croupier/sdks/go/pkg/pb/croupier/component/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Function Descriptor - Server-side function definition with UI/RBAC metadata
type FunctionDescriptor struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Id        string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`               // function id, e.g. "player.ban"
	Version   string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`     // semver, e.g. "1.2.0"
	Category  string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`   // grouping
	Risk      string                 `protobuf:"bytes,4,opt,name=risk,proto3" json:"risk,omitempty"`           // "low"|"medium"|"high"
	Entity    string                 `protobuf:"bytes,5,opt,name=entity,proto3" json:"entity,omitempty"`       // entity type, e.g. "item", "player"
	Operation string                 `protobuf:"bytes,6,opt,name=operation,proto3" json:"operation,omitempty"` // operation type, e.g. "create", "read", "update", "delete"
	Enabled   bool                   `protobuf:"varint,7,opt,name=enabled,proto3" json:"enabled,omitempty"`    // whether this function is currently enabled
	// UI/i18n/tags/menu/permissions for dynamic navigation & RBAC generation
	DisplayName *v1.I18NText       `protobuf:"bytes,20,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Summary     *v1.I18NText       `protobuf:"bytes,21,opt,name=summary,proto3" json:"summary,omitempty"`
	Tags        []string           `protobuf:"bytes,22,rep,name=tags,proto3" json:"tags,omitempty"`
	Menu        *v1.Menu           `protobuf:"bytes,23,opt,name=menu,proto3" json:"menu,omitempty"`
	Permissions *v1.PermissionSpec `protobuf:"bytes,24,opt,name=permissions,proto3" json:"permissions,omitempty"`
	// OpenAPI 3.0.3 Schema fields (JSON Schema format)
	InputSchema   string `protobuf:"bytes,30,opt,name=input_schema,json=inputSchema,proto3" json:"input_schema,omitempty"`    // JSON Schema for request body
	OutputSchema  string `protobuf:"bytes,31,opt,name=output_schema,json=outputSchema,proto3" json:"output_schema,omitempty"` // JSON Schema for response body
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FunctionDescriptor) Reset() {
	*x = FunctionDescriptor{}
	mi := &file_croupier_agent_v1_register_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionDescriptor) ProtoMessage() {}

func (x *FunctionDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_croupier_agent_v1_register_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionDescriptor.ProtoReflect.Descriptor instead.
func (*FunctionDescriptor) Descriptor() ([]byte, []int) {
	return file_croupier_agent_v1_register_proto_rawDescGZIP(), []int{0}
}

func (x *FunctionDescriptor) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FunctionDescriptor) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *FunctionDescriptor) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *FunctionDescriptor) GetRisk() string {
	if x != nil {
		return x.Risk
	}
	return ""
}

func (x *FunctionDescriptor) GetEntity() string {
	if x != nil {
		return x.Entity
	}
	return ""
}

func (x *FunctionDescriptor) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *FunctionDescriptor) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *FunctionDescriptor) GetDisplayName() *v1.I18NText {
	if x != nil {
		return x.DisplayName
	}
	return nil
}

func (x *FunctionDescriptor) GetSummary() *v1.I18NText {
	if x != nil {
		return x.Summary
	}
	return nil
}

func (x *FunctionDescriptor) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *FunctionDescriptor) GetMenu() *v1.Menu {
	if x != nil {
		return x.Menu
	}
	return nil
}

func (x *FunctionDescriptor) GetPermissions() *v1.PermissionSpec {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *FunctionDescriptor) GetInputSchema() string {
	if x != nil {
		return x.InputSchema
	}
	return ""
}

func (x *FunctionDescriptor) GetOutputSchema() string {
	if x != nil {
		return x.OutputSchema
	}
	return ""
}

// Process/service instance registered to an agent (e.g. a game server process)
type AgentProcess struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`             // unique id from SDK
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`                                        // reachable address (agent-local)
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`                                  // process/service version
	LastSeenUnix  int64                  `protobuf:"varint,4,opt,name=last_seen_unix,json=lastSeenUnix,proto3" json:"last_seen_unix,omitempty"` // unix seconds
	FunctionIds   []string               `protobuf:"bytes,5,rep,name=function_ids,json=functionIds,proto3" json:"function_ids,omitempty"`       // functions exposed by this process
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentProcess) Reset() {
	*x = AgentProcess{}
	mi := &file_croupier_agent_v1_register_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentProcess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentProcess) ProtoMessage() {}

func (x *AgentProcess) ProtoReflect() protoreflect.Message {
	mi := &file_croupier_agent_v1_register_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentProcess.ProtoReflect.Descriptor instead.
func (*AgentProcess) Descriptor() ([]byte, []int) {
	return file_croupier_agent_v1_register_proto_rawDescGZIP(), []int{1}
}

func (x *AgentProcess) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *AgentProcess) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *AgentProcess) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *AgentProcess) GetLastSeenUnix() int64 {
	if x != nil {
		return x.LastSeenUnix
	}
	return 0
}

func (x *AgentProcess) GetFunctionIds() []string {
	if x != nil {
		return x.FunctionIds
	}
	return nil
}

// Agent Registration Request
type RegisterRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	AgentId    string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`           // agent unique id
	Version    string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`                          // agent version
	Functions  []*FunctionDescriptor  `protobuf:"bytes,3,rep,name=functions,proto3" json:"functions,omitempty"`                      // summarized function list
	RpcAddr    string                 `protobuf:"bytes,4,opt,name=rpc_addr,json=rpcAddr,proto3" json:"rpc_addr,omitempty"`           // agent's reachable gRPC address (DEV ONLY)
	GameId     string                 `protobuf:"bytes,5,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`              // game scope (required for multi-game)
	Env        string                 `protobuf:"bytes,6,opt,name=env,proto3" json:"env,omitempty"`                                  // environment (optional: prod/stage/test)
	Processes  []*AgentProcess        `protobuf:"bytes,7,rep,name=processes,proto3" json:"processes,omitempty"`                      // registered processes (sdk->agent)
	TtlSeconds uint32                 `protobuf:"varint,8,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"` // session TTL (default 300s = 5min)
	// Location and labels
	Region        string            `protobuf:"bytes,10,opt,name=region,proto3" json:"region,omitempty"`                                                                           // region/zone info (e.g. "us-west-1")
	Zone          string            `protobuf:"bytes,11,opt,name=zone,proto3" json:"zone,omitempty"`                                                                               // availability zone (e.g. "us-west-1a")
	Labels        map[string]string `protobuf:"bytes,12,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // system metadata labels (os, arch, hostname, etc.)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_croupier_agent_v1_register_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_croupier_agent_v1_register_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_croupier_agent_v1_register_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RegisterRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RegisterRequest) GetFunctions() []*FunctionDescriptor {
	if x != nil {
		return x.Functions
	}
	return nil
}

func (x *RegisterRequest) GetRpcAddr() string {
	if x != nil {
		return x.RpcAddr
	}
	return ""
}

func (x *RegisterRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *RegisterRequest) GetEnv() string {
	if x != nil {
		return x.Env
	}
	return ""
}

func (x *RegisterRequest) GetProcesses() []*AgentProcess {
	if x != nil {
		return x.Processes
	}
	return nil
}

func (x *RegisterRequest) GetTtlSeconds() uint32 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

func (x *RegisterRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *RegisterRequest) GetZone() string {
	if x != nil {
		return x.Zone
	}
	return ""
}

func (x *RegisterRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

// Agent Registration Response
type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ExpireAt      int64                  `protobuf:"varint,2,opt,name=expire_at,json=expireAt,proto3" json:"expire_at,omitempty"` // epoch seconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_croupier_agent_v1_register_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_croupier_agent_v1_register_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_croupier_agent_v1_register_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RegisterResponse) GetExpireAt() int64 {
	if x != nil {
		return x.ExpireAt
	}
	return 0
}

// Agent Heartbeat Request
type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_croupier_agent_v1_register_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_croupier_agent_v1_register_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_croupier_agent_v1_register_proto_rawDescGZIP(), []int{4}
}

func (x *HeartbeatRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *HeartbeatRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// Agent Heartbeat Response
type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_croupier_agent_v1_register_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_croupier_agent_v1_register_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_croupier_agent_v1_register_proto_rawDescGZIP(), []int{5}
}

// Provider capabilities (manifest) — language-agnostic declaration
type ProviderMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Lang          string                 `protobuf:"bytes,3,opt,name=lang,proto3" json:"lang,omitempty"`
	Sdk           string                 `protobuf:"bytes,4,opt,name=sdk,proto3" json:"sdk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderMeta) Reset() {
	*x = ProviderMeta{}
	mi := &file_croupier_agent_v1_register_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderMeta) ProtoMessage() {}

func (x *ProviderMeta) ProtoReflect() protoreflect.Message {
	mi := &file_croupier_agent_v1_register_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderMeta.ProtoReflect.Descriptor instead.
func (*ProviderMeta) Descriptor() ([]byte, []int) {
	return file_croupier_agent_v1_register_proto_rawDescGZIP(), []int{6}
}

func (x *ProviderMeta) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProviderMeta) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ProviderMeta) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

func (x *ProviderMeta) GetSdk() string {
	if x != nil {
		return x.Sdk
	}
	return ""
}

// Register Capabilities Request
type RegisterCapabilitiesRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Provider       *ProviderMeta          `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	ManifestJsonGz []byte                 `protobuf:"bytes,2,opt,name=manifest_json_gz,json=manifestJsonGz,proto3" json:"manifest_json_gz,omitempty"` // gzipped manifest.json
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RegisterCapabilitiesRequest) Reset() {
	*x = RegisterCapabilitiesRequest{}
	mi := &file_croupier_agent_v1_register_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterCapabilitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterCapabilitiesRequest) ProtoMessage() {}

func (x *RegisterCapabilitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_croupier_agent_v1_register_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterCapabilitiesRequest.ProtoReflect.Descriptor instead.
func (*RegisterCapabilitiesRequest) Descriptor() ([]byte, []int) {
	return file_croupier_agent_v1_register_proto_rawDescGZIP(), []int{7}
}

func (x *RegisterCapabilitiesRequest) GetProvider() *ProviderMeta {
	if x != nil {
		return x.Provider
	}
	return nil
}

func (x *RegisterCapabilitiesRequest) GetManifestJsonGz() []byte {
	if x != nil {
		return x.ManifestJsonGz
	}
	return nil
}

// Register Capabilities Response
type RegisterCapabilitiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterCapabilitiesResponse) Reset() {
	*x = RegisterCapabilitiesResponse{}
	mi := &file_croupier_agent_v1_register_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterCapabilitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterCapabilitiesResponse) ProtoMessage() {}

func (x *RegisterCapabilitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_croupier_agent_v1_register_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterCapabilitiesResponse.ProtoReflect.Descriptor instead.
func (*RegisterCapabilitiesResponse) Descriptor() ([]byte, []int) {
	return file_croupier_agent_v1_register_proto_rawDescGZIP(), []int{8}
}

var File_croupier_agent_v1_register_proto protoreflect.FileDescriptor

const file_croupier_agent_v1_register_proto_rawDesc = "" +
	"\n" +
	" croupier/agent/v1/register.proto\x12\x11croupier.agent.v1\x1a(croupier/component/v1/dashboard_ui.proto\"\x93\x04\n" +
	"\x12FunctionDescriptor\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12\x12\n" +
	"\x04risk\x18\x04 \x01(\tR\x04risk\x12\x16\n" +
	"\x06entity\x18\x05 \x01(\tR\x06entity\x12\x1c\n" +
	"\toperation\x18\x06 \x01(\tR\toperation\x12\x18\n" +
	"\aenabled\x18\a \x01(\bR\aenabled\x12B\n" +
	"\fdisplay_name\x18\x14 \x01(\v2\x1f.croupier.component.v1.I18nTextR\vdisplayName\x129\n" +
	"\asummary\x18\x15 \x01(\v2\x1f.croupier.component.v1.I18nTextR\asummary\x12\x12\n" +
	"\x04tags\x18\x16 \x03(\tR\x04tags\x12/\n" +
	"\x04menu\x18\x17 \x01(\v2\x1b.croupier.component.v1.MenuR\x04menu\x12G\n" +
	"\vpermissions\x18\x18 \x01(\v2%.croupier.component.v1.PermissionSpecR\vpermissions\x12!\n" +
	"\finput_schema\x18\x1e \x01(\tR\vinputSchema\x12#\n" +
	"\routput_schema\x18\x1f \x01(\tR\foutputSchema\"\xa4\x01\n" +
	"\fAgentProcess\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12$\n" +
	"\x0elast_seen_unix\x18\x04 \x01(\x03R\flastSeenUnix\x12!\n" +
	"\ffunction_ids\x18\x05 \x03(\tR\vfunctionIds\"\xe0\x03\n" +
	"\x0fRegisterRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12C\n" +
	"\tfunctions\x18\x03 \x03(\v2%.croupier.agent.v1.FunctionDescriptorR\tfunctions\x12\x19\n" +
	"\brpc_addr\x18\x04 \x01(\tR\arpcAddr\x12\x17\n" +
	"\agame_id\x18\x05 \x01(\tR\x06gameId\x12\x10\n" +
	"\x03env\x18\x06 \x01(\tR\x03env\x12=\n" +
	"\tprocesses\x18\a \x03(\v2\x1f.croupier.agent.v1.AgentProcessR\tprocesses\x12\x1f\n" +
	"\vttl_seconds\x18\b \x01(\rR\n" +
	"ttlSeconds\x12\x16\n" +
	"\x06region\x18\n" +
	" \x01(\tR\x06region\x12\x12\n" +
	"\x04zone\x18\v \x01(\tR\x04zone\x12F\n" +
	"\x06labels\x18\f \x03(\v2..croupier.agent.v1.RegisterRequest.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"N\n" +
	"\x10RegisterResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\texpire_at\x18\x02 \x01(\x03R\bexpireAt\"L\n" +
	"\x10HeartbeatRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\"\x13\n" +
	"\x11HeartbeatResponse\"^\n" +
	"\fProviderMeta\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x12\n" +
	"\x04lang\x18\x03 \x01(\tR\x04lang\x12\x10\n" +
	"\x03sdk\x18\x04 \x01(\tR\x03sdk\"\x84\x01\n" +
	"\x1bRegisterCapabilitiesRequest\x12;\n" +
	"\bprovider\x18\x01 \x01(\v2\x1f.croupier.agent.v1.ProviderMetaR\bprovider\x12(\n" +
	"\x10manifest_json_gz\x18\x02 \x01(\fR\x0emanifestJsonGz\"\x1e\n" +
	"\x1cRegisterCapabilitiesResponseBo\n" +
	"$io.github.cuihairu.croupier.agent.v1P\x01ZEgithub.com/cuihairu/croupier/sdks/go/pkg/pb/croupier/agent/v1;agentv1b\x06proto3"

var (
	file_croupier_agent_v1_register_proto_rawDescOnce sync.Once
	file_croupier_agent_v1_register_proto_rawDescData []byte
)

func file_croupier_agent_v1_register_proto_rawDescGZIP() []byte {
	file_croupier_agent_v1_register_proto_rawDescOnce.Do(func() {
		file_croupier_agent_v1_register_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_croupier_agent_v1_register_proto_rawDesc), len(file_croupier_agent_v1_register_proto_rawDesc)))
	})
	return file_croupier_agent_v1_register_proto_rawDescData
}

var file_croupier_agent_v1_register_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_croupier_agent_v1_register_proto_goTypes = []any{
	(*FunctionDescriptor)(nil),           // 0: croupier.agent.v1.FunctionDescriptor
	(*AgentProcess)(nil),                 // 1: croupier.agent.v1.AgentProcess
	(*RegisterRequest)(nil),              // 2: croupier.agent.v1.RegisterRequest
	(*RegisterResponse)(nil),             // 3: croupier.agent.v1.RegisterResponse
	(*HeartbeatRequest)(nil),             // 4: croupier.agent.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),            // 5: croupier.agent.v1.HeartbeatResponse
	(*ProviderMeta)(nil),                 // 6: croupier.agent.v1.ProviderMeta
	(*RegisterCapabilitiesRequest)(nil),  // 7: croupier.agent.v1.RegisterCapabilitiesRequest
	(*RegisterCapabilitiesResponse)(nil), // 8: croupier.agent.v1.RegisterCapabilitiesResponse
	nil,                                  // 9: croupier.agent.v1.RegisterRequest.LabelsEntry
	(*v1.I18NText)(nil),                  // 10: croupier.component.v1.I18nText
	(*v1.Menu)(nil),                      // 11: croupier.component.v1.Menu
	(*v1.PermissionSpec)(nil),            // 12: croupier.component.v1.PermissionSpec
}
var file_croupier_agent_v1_register_proto_depIdxs = []int32{
	10, // 0: croupier.agent.v1.FunctionDescriptor.display_name:type_name -> croupier.component.v1.I18nText
	10, // 1: croupier.agent.v1.FunctionDescriptor.summary:type_name -> croupier.component.v1.I18nText
	11, // 2: croupier.agent.v1.FunctionDescriptor.menu:type_name -> croupier.component.v1.Menu
	12, // 3: croupier.agent.v1.FunctionDescriptor.permissions:type_name -> croupier.component.v1.PermissionSpec
	0,  // 4: croupier.agent.v1.RegisterRequest.functions:type_name -> croupier.agent.v1.FunctionDescriptor
	1,  // 5: croupier.agent.v1.RegisterRequest.processes:type_name -> croupier.agent.v1.AgentProcess
	9,  // 6: croupier.agent.v1.RegisterRequest.labels:type_name -> croupier.agent.v1.RegisterRequest.LabelsEntry
	6,  // 7: croupier.agent.v1.RegisterCapabilitiesRequest.provider:type_name -> croupier.agent.v1.ProviderMeta
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_croupier_agent_v1_register_proto_init() }
func file_croupier_agent_v1_register_proto_init() {
	if File_croupier_agent_v1_register_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_croupier_agent_v1_register_proto_rawDesc), len(file_croupier_agent_v1_register_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_croupier_agent_v1_register_proto_goTypes,
		DependencyIndexes: file_croupier_agent_v1_register_proto_depIdxs,
		MessageInfos:      file_croupier_agent_v1_register_proto_msgTypes,
	}.Build()
	File_croupier_agent_v1_register_proto = out.File
	file_croupier_agent_v1_register_proto_goTypes = nil
	file_croupier_agent_v1_register_proto_depIdxs = nil
}
