// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: croupier/sdk/v1/function.proto

package sdkv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	FunctionClientService_Invoke_FullMethodName    = "/croupier.sdk.v1.FunctionClientService/Invoke"
	FunctionClientService_StartJob_FullMethodName  = "/croupier.sdk.v1.FunctionClientService/StartJob"
	FunctionClientService_StreamJob_FullMethodName = "/croupier.sdk.v1.FunctionClientService/StreamJob"
	FunctionClientService_CancelJob_FullMethodName = "/croupier.sdk.v1.FunctionClientService/CancelJob"
)

// FunctionClientServiceClient is the client API for FunctionClientService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FunctionClientServiceClient interface {
	// Synchronous function invocation
	Invoke(ctx context.Context, in *InvokeRequest, opts ...grpc.CallOption) (*InvokeResponse, error)
	// Asynchronous job starting
	StartJob(ctx context.Context, in *InvokeRequest, opts ...grpc.CallOption) (*StartJobResponse, error)
	// Stream job events for async operations
	StreamJob(ctx context.Context, in *JobStreamRequest, opts ...grpc.CallOption) (FunctionClientService_StreamJobClient, error)
	// Cancel a running job
	CancelJob(ctx context.Context, in *CancelJobRequest, opts ...grpc.CallOption) (*StartJobResponse, error)
}

type functionClientServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFunctionClientServiceClient(cc grpc.ClientConnInterface) FunctionClientServiceClient {
	return &functionClientServiceClient{cc}
}

func (c *functionClientServiceClient) Invoke(ctx context.Context, in *InvokeRequest, opts ...grpc.CallOption) (*InvokeResponse, error) {
	out := new(InvokeResponse)
	err := c.cc.Invoke(ctx, FunctionClientService_Invoke_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *functionClientServiceClient) StartJob(ctx context.Context, in *InvokeRequest, opts ...grpc.CallOption) (*StartJobResponse, error) {
	out := new(StartJobResponse)
	err := c.cc.Invoke(ctx, FunctionClientService_StartJob_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *functionClientServiceClient) StreamJob(ctx context.Context, in *JobStreamRequest, opts ...grpc.CallOption) (FunctionClientService_StreamJobClient, error) {
	stream, err := c.cc.NewStream(ctx, &FunctionClientService_ServiceDesc.Streams[0], FunctionClientService_StreamJob_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &functionClientServiceStreamJobClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type FunctionClientService_StreamJobClient interface {
	Recv() (*JobEvent, error)
	grpc.ClientStream
}

type functionClientServiceStreamJobClient struct {
	grpc.ClientStream
}

func (x *functionClientServiceStreamJobClient) Recv() (*JobEvent, error) {
	m := new(JobEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *functionClientServiceClient) CancelJob(ctx context.Context, in *CancelJobRequest, opts ...grpc.CallOption) (*StartJobResponse, error) {
	out := new(StartJobResponse)
	err := c.cc.Invoke(ctx, FunctionClientService_CancelJob_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FunctionClientServiceServer is the server API for FunctionClientService service.
// All implementations must embed UnimplementedFunctionClientServiceServer
// for forward compatibility
type FunctionClientServiceServer interface {
	// Synchronous function invocation
	Invoke(context.Context, *InvokeRequest) (*InvokeResponse, error)
	// Asynchronous job starting
	StartJob(context.Context, *InvokeRequest) (*StartJobResponse, error)
	// Stream job events for async operations
	StreamJob(*JobStreamRequest, FunctionClientService_StreamJobServer) error
	// Cancel a running job
	CancelJob(context.Context, *CancelJobRequest) (*StartJobResponse, error)
	mustEmbedUnimplementedFunctionClientServiceServer()
}

// UnimplementedFunctionClientServiceServer must be embedded to have forward compatible implementations.
type UnimplementedFunctionClientServiceServer struct {
}

func (UnimplementedFunctionClientServiceServer) Invoke(context.Context, *InvokeRequest) (*InvokeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Invoke not implemented")
}
func (UnimplementedFunctionClientServiceServer) StartJob(context.Context, *InvokeRequest) (*StartJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartJob not implemented")
}
func (UnimplementedFunctionClientServiceServer) StreamJob(*JobStreamRequest, FunctionClientService_StreamJobServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamJob not implemented")
}
func (UnimplementedFunctionClientServiceServer) CancelJob(context.Context, *CancelJobRequest) (*StartJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelJob not implemented")
}
func (UnimplementedFunctionClientServiceServer) mustEmbedUnimplementedFunctionClientServiceServer() {}

// UnsafeFunctionClientServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FunctionClientServiceServer will
// result in compilation errors.
type UnsafeFunctionClientServiceServer interface {
	mustEmbedUnimplementedFunctionClientServiceServer()
}

func RegisterFunctionClientServiceServer(s grpc.ServiceRegistrar, srv FunctionClientServiceServer) {
	s.RegisterService(&FunctionClientService_ServiceDesc, srv)
}

func _FunctionClientService_Invoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvokeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FunctionClientServiceServer).Invoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FunctionClientService_Invoke_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FunctionClientServiceServer).Invoke(ctx, req.(*InvokeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FunctionClientService_StartJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvokeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FunctionClientServiceServer).StartJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FunctionClientService_StartJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FunctionClientServiceServer).StartJob(ctx, req.(*InvokeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FunctionClientService_StreamJob_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(JobStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FunctionClientServiceServer).StreamJob(m, &functionClientServiceStreamJobServer{stream})
}

type FunctionClientService_StreamJobServer interface {
	Send(*JobEvent) error
	grpc.ServerStream
}

type functionClientServiceStreamJobServer struct {
	grpc.ServerStream
}

func (x *functionClientServiceStreamJobServer) Send(m *JobEvent) error {
	return x.ServerStream.SendMsg(m)
}

func _FunctionClientService_CancelJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FunctionClientServiceServer).CancelJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FunctionClientService_CancelJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FunctionClientServiceServer).CancelJob(ctx, req.(*CancelJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FunctionClientService_ServiceDesc is the grpc.ServiceDesc for FunctionClientService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FunctionClientService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "croupier.sdk.v1.FunctionClientService",
	HandlerType: (*FunctionClientServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Invoke",
			Handler:    _FunctionClientService_Invoke_Handler,
		},
		{
			MethodName: "StartJob",
			Handler:    _FunctionClientService_StartJob_Handler,
		},
		{
			MethodName: "CancelJob",
			Handler:    _FunctionClientService_CancelJob_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamJob",
			Handler:       _FunctionClientService_StreamJob_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "croupier/sdk/v1/function.proto",
}
