// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: croupier/sdk/v1/provider.proto

package sdkv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Local function registration from game servers to Agent
// Based on OpenAPI 3.0.3 Operation Object fields
type LocalFunctionDescriptor struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Id      string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`           // Unique function identifier
	Version string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"` // Function version
	// OpenAPI 3.0.3 Operation Object fields
	Tags        []string `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`                                  // Tags for grouping operations
	Summary     string   `protobuf:"bytes,4,opt,name=summary,proto3" json:"summary,omitempty"`                            // Short summary
	Description string   `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`                    // Detailed description (supports markdown)
	OperationId string   `protobuf:"bytes,6,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"` // Unique operation ID
	Deprecated  bool     `protobuf:"varint,7,opt,name=deprecated,proto3" json:"deprecated,omitempty"`                     // Deprecation status
	// OpenAPI 3.0.3 Schema fields (JSON Schema format)
	InputSchema  string `protobuf:"bytes,8,opt,name=input_schema,json=inputSchema,proto3" json:"input_schema,omitempty"`    // JSON Schema for request body
	OutputSchema string `protobuf:"bytes,9,opt,name=output_schema,json=outputSchema,proto3" json:"output_schema,omitempty"` // JSON Schema for response body
	// OpenAPI 3.0.3 Extension fields (x-* prefix)
	Category      string `protobuf:"bytes,10,opt,name=category,proto3" json:"category,omitempty"`   // x-category: function category (e.g., "game", "system", "player")
	Risk          string `protobuf:"bytes,11,opt,name=risk,proto3" json:"risk,omitempty"`           // x-risk: risk level (e.g., "safe", "danger", "warning")
	Entity        string `protobuf:"bytes,12,opt,name=entity,proto3" json:"entity,omitempty"`       // x-entity: associated entity type (e.g., "Player", "Item", "Guild")
	Operation     string `protobuf:"bytes,13,opt,name=operation,proto3" json:"operation,omitempty"` // x-operation: CRUD operation type (e.g., "create", "read", "update", "delete", "custom")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocalFunctionDescriptor) Reset() {
	*x = LocalFunctionDescriptor{}
	mi := &file_croupier_sdk_v1_provider_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalFunctionDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalFunctionDescriptor) ProtoMessage() {}

func (x *LocalFunctionDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_croupier_sdk_v1_provider_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalFunctionDescriptor.ProtoReflect.Descriptor instead.
func (*LocalFunctionDescriptor) Descriptor() ([]byte, []int) {
	return file_croupier_sdk_v1_provider_proto_rawDescGZIP(), []int{0}
}

func (x *LocalFunctionDescriptor) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LocalFunctionDescriptor) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *LocalFunctionDescriptor) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *LocalFunctionDescriptor) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *LocalFunctionDescriptor) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *LocalFunctionDescriptor) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *LocalFunctionDescriptor) GetDeprecated() bool {
	if x != nil {
		return x.Deprecated
	}
	return false
}

func (x *LocalFunctionDescriptor) GetInputSchema() string {
	if x != nil {
		return x.InputSchema
	}
	return ""
}

func (x *LocalFunctionDescriptor) GetOutputSchema() string {
	if x != nil {
		return x.OutputSchema
	}
	return ""
}

func (x *LocalFunctionDescriptor) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *LocalFunctionDescriptor) GetRisk() string {
	if x != nil {
		return x.Risk
	}
	return ""
}

func (x *LocalFunctionDescriptor) GetEntity() string {
	if x != nil {
		return x.Entity
	}
	return ""
}

func (x *LocalFunctionDescriptor) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

type RegisterLocalRequest struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	ServiceId     string                     `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Version       string                     `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	RpcAddr       string                     `protobuf:"bytes,3,opt,name=rpc_addr,json=rpcAddr,proto3" json:"rpc_addr,omitempty"`
	Functions     []*LocalFunctionDescriptor `protobuf:"bytes,4,rep,name=functions,proto3" json:"functions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterLocalRequest) Reset() {
	*x = RegisterLocalRequest{}
	mi := &file_croupier_sdk_v1_provider_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterLocalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterLocalRequest) ProtoMessage() {}

func (x *RegisterLocalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_croupier_sdk_v1_provider_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterLocalRequest.ProtoReflect.Descriptor instead.
func (*RegisterLocalRequest) Descriptor() ([]byte, []int) {
	return file_croupier_sdk_v1_provider_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterLocalRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *RegisterLocalRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RegisterLocalRequest) GetRpcAddr() string {
	if x != nil {
		return x.RpcAddr
	}
	return ""
}

func (x *RegisterLocalRequest) GetFunctions() []*LocalFunctionDescriptor {
	if x != nil {
		return x.Functions
	}
	return nil
}

type RegisterLocalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterLocalResponse) Reset() {
	*x = RegisterLocalResponse{}
	mi := &file_croupier_sdk_v1_provider_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterLocalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterLocalResponse) ProtoMessage() {}

func (x *RegisterLocalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_croupier_sdk_v1_provider_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterLocalResponse.ProtoReflect.Descriptor instead.
func (*RegisterLocalResponse) Descriptor() ([]byte, []int) {
	return file_croupier_sdk_v1_provider_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterLocalResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_croupier_sdk_v1_provider_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_croupier_sdk_v1_provider_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_croupier_sdk_v1_provider_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *HeartbeatRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_croupier_sdk_v1_provider_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_croupier_sdk_v1_provider_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_croupier_sdk_v1_provider_proto_rawDescGZIP(), []int{4}
}

// Query local registered instances
type LocalInstance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	LastSeen      string                 `protobuf:"bytes,4,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocalInstance) Reset() {
	*x = LocalInstance{}
	mi := &file_croupier_sdk_v1_provider_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalInstance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalInstance) ProtoMessage() {}

func (x *LocalInstance) ProtoReflect() protoreflect.Message {
	mi := &file_croupier_sdk_v1_provider_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalInstance.ProtoReflect.Descriptor instead.
func (*LocalInstance) Descriptor() ([]byte, []int) {
	return file_croupier_sdk_v1_provider_proto_rawDescGZIP(), []int{5}
}

func (x *LocalInstance) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *LocalInstance) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *LocalInstance) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *LocalInstance) GetLastSeen() string {
	if x != nil {
		return x.LastSeen
	}
	return ""
}

type LocalFunction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Instances     []*LocalInstance       `protobuf:"bytes,2,rep,name=instances,proto3" json:"instances,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocalFunction) Reset() {
	*x = LocalFunction{}
	mi := &file_croupier_sdk_v1_provider_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalFunction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalFunction) ProtoMessage() {}

func (x *LocalFunction) ProtoReflect() protoreflect.Message {
	mi := &file_croupier_sdk_v1_provider_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalFunction.ProtoReflect.Descriptor instead.
func (*LocalFunction) Descriptor() ([]byte, []int) {
	return file_croupier_sdk_v1_provider_proto_rawDescGZIP(), []int{6}
}

func (x *LocalFunction) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LocalFunction) GetInstances() []*LocalInstance {
	if x != nil {
		return x.Instances
	}
	return nil
}

type ListLocalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLocalRequest) Reset() {
	*x = ListLocalRequest{}
	mi := &file_croupier_sdk_v1_provider_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLocalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLocalRequest) ProtoMessage() {}

func (x *ListLocalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_croupier_sdk_v1_provider_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLocalRequest.ProtoReflect.Descriptor instead.
func (*ListLocalRequest) Descriptor() ([]byte, []int) {
	return file_croupier_sdk_v1_provider_proto_rawDescGZIP(), []int{7}
}

type ListLocalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Functions     []*LocalFunction       `protobuf:"bytes,1,rep,name=functions,proto3" json:"functions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLocalResponse) Reset() {
	*x = ListLocalResponse{}
	mi := &file_croupier_sdk_v1_provider_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLocalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLocalResponse) ProtoMessage() {}

func (x *ListLocalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_croupier_sdk_v1_provider_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLocalResponse.ProtoReflect.Descriptor instead.
func (*ListLocalResponse) Descriptor() ([]byte, []int) {
	return file_croupier_sdk_v1_provider_proto_rawDescGZIP(), []int{8}
}

func (x *ListLocalResponse) GetFunctions() []*LocalFunction {
	if x != nil {
		return x.Functions
	}
	return nil
}

// Query job result from Agent (best-effort)
type GetJobResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobResultRequest) Reset() {
	*x = GetJobResultRequest{}
	mi := &file_croupier_sdk_v1_provider_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobResultRequest) ProtoMessage() {}

func (x *GetJobResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_croupier_sdk_v1_provider_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobResultRequest.ProtoReflect.Descriptor instead.
func (*GetJobResultRequest) Descriptor() ([]byte, []int) {
	return file_croupier_sdk_v1_provider_proto_rawDescGZIP(), []int{9}
}

func (x *GetJobResultRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type GetJobResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         string                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobResultResponse) Reset() {
	*x = GetJobResultResponse{}
	mi := &file_croupier_sdk_v1_provider_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobResultResponse) ProtoMessage() {}

func (x *GetJobResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_croupier_sdk_v1_provider_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobResultResponse.ProtoReflect.Descriptor instead.
func (*GetJobResultResponse) Descriptor() ([]byte, []int) {
	return file_croupier_sdk_v1_provider_proto_rawDescGZIP(), []int{10}
}

func (x *GetJobResultResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *GetJobResultResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *GetJobResultResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_croupier_sdk_v1_provider_proto protoreflect.FileDescriptor

const file_croupier_sdk_v1_provider_proto_rawDesc = "" +
	"\n" +
	"\x1ecroupier/sdk/v1/provider.proto\x12\x0fcroupier.sdk.v1\"\x84\x03\n" +
	"\x17LocalFunctionDescriptor\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x12\n" +
	"\x04tags\x18\x03 \x03(\tR\x04tags\x12\x18\n" +
	"\asummary\x18\x04 \x01(\tR\asummary\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12!\n" +
	"\foperation_id\x18\x06 \x01(\tR\voperationId\x12\x1e\n" +
	"\n" +
	"deprecated\x18\a \x01(\bR\n" +
	"deprecated\x12!\n" +
	"\finput_schema\x18\b \x01(\tR\vinputSchema\x12#\n" +
	"\routput_schema\x18\t \x01(\tR\foutputSchema\x12\x1a\n" +
	"\bcategory\x18\n" +
	" \x01(\tR\bcategory\x12\x12\n" +
	"\x04risk\x18\v \x01(\tR\x04risk\x12\x16\n" +
	"\x06entity\x18\f \x01(\tR\x06entity\x12\x1c\n" +
	"\toperation\x18\r \x01(\tR\toperation\"\xb2\x01\n" +
	"\x14RegisterLocalRequest\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x19\n" +
	"\brpc_addr\x18\x03 \x01(\tR\arpcAddr\x12F\n" +
	"\tfunctions\x18\x04 \x03(\v2(.croupier.sdk.v1.LocalFunctionDescriptorR\tfunctions\"6\n" +
	"\x15RegisterLocalResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"P\n" +
	"\x10HeartbeatRequest\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\"\x13\n" +
	"\x11HeartbeatResponse\"y\n" +
	"\rLocalInstance\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x1b\n" +
	"\tlast_seen\x18\x04 \x01(\tR\blastSeen\"]\n" +
	"\rLocalFunction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12<\n" +
	"\tinstances\x18\x02 \x03(\v2\x1e.croupier.sdk.v1.LocalInstanceR\tinstances\"\x12\n" +
	"\x10ListLocalRequest\"Q\n" +
	"\x11ListLocalResponse\x12<\n" +
	"\tfunctions\x18\x01 \x03(\v2\x1e.croupier.sdk.v1.LocalFunctionR\tfunctions\",\n" +
	"\x13GetJobResultRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"\\\n" +
	"\x14GetJobResultResponse\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05errorBa\n" +
	"\"io.github.cuihairu.croupier.sdk.v1P\x01Z9github.com/cuihairu/croupier/sdks/go/pkg/pb/croupier/sdk/v1;sdkv1b\x06proto3"

var (
	file_croupier_sdk_v1_provider_proto_rawDescOnce sync.Once
	file_croupier_sdk_v1_provider_proto_rawDescData []byte
)

func file_croupier_sdk_v1_provider_proto_rawDescGZIP() []byte {
	file_croupier_sdk_v1_provider_proto_rawDescOnce.Do(func() {
		file_croupier_sdk_v1_provider_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_croupier_sdk_v1_provider_proto_rawDesc), len(file_croupier_sdk_v1_provider_proto_rawDesc)))
	})
	return file_croupier_sdk_v1_provider_proto_rawDescData
}

var file_croupier_sdk_v1_provider_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_croupier_sdk_v1_provider_proto_goTypes = []any{
	(*LocalFunctionDescriptor)(nil), // 0: croupier.sdk.v1.LocalFunctionDescriptor
	(*RegisterLocalRequest)(nil),    // 1: croupier.sdk.v1.RegisterLocalRequest
	(*RegisterLocalResponse)(nil),   // 2: croupier.sdk.v1.RegisterLocalResponse
	(*HeartbeatRequest)(nil),        // 3: croupier.sdk.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),       // 4: croupier.sdk.v1.HeartbeatResponse
	(*LocalInstance)(nil),           // 5: croupier.sdk.v1.LocalInstance
	(*LocalFunction)(nil),           // 6: croupier.sdk.v1.LocalFunction
	(*ListLocalRequest)(nil),        // 7: croupier.sdk.v1.ListLocalRequest
	(*ListLocalResponse)(nil),       // 8: croupier.sdk.v1.ListLocalResponse
	(*GetJobResultRequest)(nil),     // 9: croupier.sdk.v1.GetJobResultRequest
	(*GetJobResultResponse)(nil),    // 10: croupier.sdk.v1.GetJobResultResponse
}
var file_croupier_sdk_v1_provider_proto_depIdxs = []int32{
	0, // 0: croupier.sdk.v1.RegisterLocalRequest.functions:type_name -> croupier.sdk.v1.LocalFunctionDescriptor
	5, // 1: croupier.sdk.v1.LocalFunction.instances:type_name -> croupier.sdk.v1.LocalInstance
	6, // 2: croupier.sdk.v1.ListLocalResponse.functions:type_name -> croupier.sdk.v1.LocalFunction
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_croupier_sdk_v1_provider_proto_init() }
func file_croupier_sdk_v1_provider_proto_init() {
	if File_croupier_sdk_v1_provider_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_croupier_sdk_v1_provider_proto_rawDesc), len(file_croupier_sdk_v1_provider_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_croupier_sdk_v1_provider_proto_goTypes,
		DependencyIndexes: file_croupier_sdk_v1_provider_proto_depIdxs,
		MessageInfos:      file_croupier_sdk_v1_provider_proto_msgTypes,
	}.Build()
	File_croupier_sdk_v1_provider_proto = out.File
	file_croupier_sdk_v1_provider_proto_goTypes = nil
	file_croupier_sdk_v1_provider_proto_depIdxs = nil
}
