// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: croupier/ops/v1/ops.proto

package opsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProcessState int32

const (
	ProcessState_PROCESS_STATE_UNSPECIFIED ProcessState = 0
	ProcessState_PROCESS_STATE_RUNNING     ProcessState = 1
	ProcessState_PROCESS_STATE_STOPPED     ProcessState = 2
	ProcessState_PROCESS_STATE_FAILED      ProcessState = 3
	ProcessState_PROCESS_STATE_STARTING    ProcessState = 4
	ProcessState_PROCESS_STATE_STOPPING    ProcessState = 5
)

// Enum value maps for ProcessState.
var (
	ProcessState_name = map[int32]string{
		0: "PROCESS_STATE_UNSPECIFIED",
		1: "PROCESS_STATE_RUNNING",
		2: "PROCESS_STATE_STOPPED",
		3: "PROCESS_STATE_FAILED",
		4: "PROCESS_STATE_STARTING",
		5: "PROCESS_STATE_STOPPING",
	}
	ProcessState_value = map[string]int32{
		"PROCESS_STATE_UNSPECIFIED": 0,
		"PROCESS_STATE_RUNNING":     1,
		"PROCESS_STATE_STOPPED":     2,
		"PROCESS_STATE_FAILED":      3,
		"PROCESS_STATE_STARTING":    4,
		"PROCESS_STATE_STOPPING":    5,
	}
)

func (x ProcessState) Enum() *ProcessState {
	p := new(ProcessState)
	*p = x
	return p
}

func (x ProcessState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProcessState) Descriptor() protoreflect.EnumDescriptor {
	return file_croupier_ops_v1_ops_proto_enumTypes[0].Descriptor()
}

func (ProcessState) Type() protoreflect.EnumType {
	return &file_croupier_ops_v1_ops_proto_enumTypes[0]
}

func (x ProcessState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProcessState.Descriptor instead.
func (ProcessState) EnumDescriptor() ([]byte, []int) {
	return file_croupier_ops_v1_ops_proto_rawDescGZIP(), []int{0}
}

// MetricsReport contains system metrics from an agent.
type MetricsReport struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	AgentId   string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// CPU metrics
	Cpu *CpuMetrics `protobuf:"bytes,3,opt,name=cpu,proto3" json:"cpu,omitempty"`
	// Memory metrics
	Memory *MemoryMetrics `protobuf:"bytes,4,opt,name=memory,proto3" json:"memory,omitempty"`
	// Disk metrics
	Disks []*DiskMetrics `protobuf:"bytes,5,rep,name=disks,proto3" json:"disks,omitempty"`
	// Network metrics
	Networks []*NetworkMetrics `protobuf:"bytes,6,rep,name=networks,proto3" json:"networks,omitempty"`
	// Process metrics
	Processes []*ProcessMetrics `protobuf:"bytes,7,rep,name=processes,proto3" json:"processes,omitempty"`
	// Custom metrics (key-value pairs)
	Custom        map[string]float64 `protobuf:"bytes,8,rep,name=custom,proto3" json:"custom,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsReport) Reset() {
	*x = MetricsReport{}
	mi := &file_croupier_ops_v1_ops_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsReport) ProtoMessage() {}

func (x *MetricsReport) ProtoReflect() protoreflect.Message {
	mi := &file_croupier_ops_v1_ops_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsReport.ProtoReflect.Descriptor instead.
func (*MetricsReport) Descriptor() ([]byte, []int) {
	return file_croupier_ops_v1_ops_proto_rawDescGZIP(), []int{0}
}

func (x *MetricsReport) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *MetricsReport) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *MetricsReport) GetCpu() *CpuMetrics {
	if x != nil {
		return x.Cpu
	}
	return nil
}

func (x *MetricsReport) GetMemory() *MemoryMetrics {
	if x != nil {
		return x.Memory
	}
	return nil
}

func (x *MetricsReport) GetDisks() []*DiskMetrics {
	if x != nil {
		return x.Disks
	}
	return nil
}

func (x *MetricsReport) GetNetworks() []*NetworkMetrics {
	if x != nil {
		return x.Networks
	}
	return nil
}

func (x *MetricsReport) GetProcesses() []*ProcessMetrics {
	if x != nil {
		return x.Processes
	}
	return nil
}

func (x *MetricsReport) GetCustom() map[string]float64 {
	if x != nil {
		return x.Custom
	}
	return nil
}

type CpuMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UsagePercent  float64                `protobuf:"fixed64,1,opt,name=usage_percent,json=usagePercent,proto3" json:"usage_percent,omitempty"` // Overall CPU usage percentage (0-100)
	Cores         int32                  `protobuf:"varint,2,opt,name=cores,proto3" json:"cores,omitempty"`                                    // Number of CPU cores
	PerCore       []float64              `protobuf:"fixed64,3,rep,packed,name=per_core,json=perCore,proto3" json:"per_core,omitempty"`         // Per-core usage percentage
	Load_1M       float64                `protobuf:"fixed64,4,opt,name=load_1m,json=load1m,proto3" json:"load_1m,omitempty"`                   // 1-minute load average
	Load_5M       float64                `protobuf:"fixed64,5,opt,name=load_5m,json=load5m,proto3" json:"load_5m,omitempty"`                   // 5-minute load average
	Load_15M      float64                `protobuf:"fixed64,6,opt,name=load_15m,json=load15m,proto3" json:"load_15m,omitempty"`                // 15-minute load average
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CpuMetrics) Reset() {
	*x = CpuMetrics{}
	mi := &file_croupier_ops_v1_ops_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CpuMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CpuMetrics) ProtoMessage() {}

func (x *CpuMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_croupier_ops_v1_ops_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CpuMetrics.ProtoReflect.Descriptor instead.
func (*CpuMetrics) Descriptor() ([]byte, []int) {
	return file_croupier_ops_v1_ops_proto_rawDescGZIP(), []int{1}
}

func (x *CpuMetrics) GetUsagePercent() float64 {
	if x != nil {
		return x.UsagePercent
	}
	return 0
}

func (x *CpuMetrics) GetCores() int32 {
	if x != nil {
		return x.Cores
	}
	return 0
}

func (x *CpuMetrics) GetPerCore() []float64 {
	if x != nil {
		return x.PerCore
	}
	return nil
}

func (x *CpuMetrics) GetLoad_1M() float64 {
	if x != nil {
		return x.Load_1M
	}
	return 0
}

func (x *CpuMetrics) GetLoad_5M() float64 {
	if x != nil {
		return x.Load_5M
	}
	return 0
}

func (x *CpuMetrics) GetLoad_15M() float64 {
	if x != nil {
		return x.Load_15M
	}
	return 0
}

type MemoryMetrics struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TotalBytes     uint64                 `protobuf:"varint,1,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`             // Total memory in bytes
	UsedBytes      uint64                 `protobuf:"varint,2,opt,name=used_bytes,json=usedBytes,proto3" json:"used_bytes,omitempty"`                // Used memory in bytes
	AvailableBytes uint64                 `protobuf:"varint,3,opt,name=available_bytes,json=availableBytes,proto3" json:"available_bytes,omitempty"` // Available memory in bytes
	UsagePercent   float64                `protobuf:"fixed64,4,opt,name=usage_percent,json=usagePercent,proto3" json:"usage_percent,omitempty"`      // Memory usage percentage
	SwapTotal      uint64                 `protobuf:"varint,5,opt,name=swap_total,json=swapTotal,proto3" json:"swap_total,omitempty"`                // Swap total in bytes
	SwapUsed       uint64                 `protobuf:"varint,6,opt,name=swap_used,json=swapUsed,proto3" json:"swap_used,omitempty"`                   // Swap used in bytes
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MemoryMetrics) Reset() {
	*x = MemoryMetrics{}
	mi := &file_croupier_ops_v1_ops_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryMetrics) ProtoMessage() {}

func (x *MemoryMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_croupier_ops_v1_ops_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryMetrics.ProtoReflect.Descriptor instead.
func (*MemoryMetrics) Descriptor() ([]byte, []int) {
	return file_croupier_ops_v1_ops_proto_rawDescGZIP(), []int{2}
}

func (x *MemoryMetrics) GetTotalBytes() uint64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *MemoryMetrics) GetUsedBytes() uint64 {
	if x != nil {
		return x.UsedBytes
	}
	return 0
}

func (x *MemoryMetrics) GetAvailableBytes() uint64 {
	if x != nil {
		return x.AvailableBytes
	}
	return 0
}

func (x *MemoryMetrics) GetUsagePercent() float64 {
	if x != nil {
		return x.UsagePercent
	}
	return 0
}

func (x *MemoryMetrics) GetSwapTotal() uint64 {
	if x != nil {
		return x.SwapTotal
	}
	return 0
}

func (x *MemoryMetrics) GetSwapUsed() uint64 {
	if x != nil {
		return x.SwapUsed
	}
	return 0
}

type DiskMetrics struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MountPoint     string                 `protobuf:"bytes,1,opt,name=mount_point,json=mountPoint,proto3" json:"mount_point,omitempty"`              // Mount point path
	Device         string                 `protobuf:"bytes,2,opt,name=device,proto3" json:"device,omitempty"`                                        // Device name
	FsType         string                 `protobuf:"bytes,3,opt,name=fs_type,json=fsType,proto3" json:"fs_type,omitempty"`                          // Filesystem type
	TotalBytes     uint64                 `protobuf:"varint,4,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`             // Total disk space
	UsedBytes      uint64                 `protobuf:"varint,5,opt,name=used_bytes,json=usedBytes,proto3" json:"used_bytes,omitempty"`                // Used disk space
	AvailableBytes uint64                 `protobuf:"varint,6,opt,name=available_bytes,json=availableBytes,proto3" json:"available_bytes,omitempty"` // Available disk space
	UsagePercent   float64                `protobuf:"fixed64,7,opt,name=usage_percent,json=usagePercent,proto3" json:"usage_percent,omitempty"`      // Disk usage percentage
	InodeTotal     uint64                 `protobuf:"varint,8,opt,name=inode_total,json=inodeTotal,proto3" json:"inode_total,omitempty"`             // Total inodes
	InodeUsed      uint64                 `protobuf:"varint,9,opt,name=inode_used,json=inodeUsed,proto3" json:"inode_used,omitempty"`                // Used inodes
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DiskMetrics) Reset() {
	*x = DiskMetrics{}
	mi := &file_croupier_ops_v1_ops_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskMetrics) ProtoMessage() {}

func (x *DiskMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_croupier_ops_v1_ops_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskMetrics.ProtoReflect.Descriptor instead.
func (*DiskMetrics) Descriptor() ([]byte, []int) {
	return file_croupier_ops_v1_ops_proto_rawDescGZIP(), []int{3}
}

func (x *DiskMetrics) GetMountPoint() string {
	if x != nil {
		return x.MountPoint
	}
	return ""
}

func (x *DiskMetrics) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *DiskMetrics) GetFsType() string {
	if x != nil {
		return x.FsType
	}
	return ""
}

func (x *DiskMetrics) GetTotalBytes() uint64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *DiskMetrics) GetUsedBytes() uint64 {
	if x != nil {
		return x.UsedBytes
	}
	return 0
}

func (x *DiskMetrics) GetAvailableBytes() uint64 {
	if x != nil {
		return x.AvailableBytes
	}
	return 0
}

func (x *DiskMetrics) GetUsagePercent() float64 {
	if x != nil {
		return x.UsagePercent
	}
	return 0
}

func (x *DiskMetrics) GetInodeTotal() uint64 {
	if x != nil {
		return x.InodeTotal
	}
	return 0
}

func (x *DiskMetrics) GetInodeUsed() uint64 {
	if x != nil {
		return x.InodeUsed
	}
	return 0
}

type NetworkMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Interface     string                 `protobuf:"bytes,1,opt,name=interface,proto3" json:"interface,omitempty"`                         // Network interface name
	BytesSent     uint64                 `protobuf:"varint,2,opt,name=bytes_sent,json=bytesSent,proto3" json:"bytes_sent,omitempty"`       // Total bytes sent
	BytesRecv     uint64                 `protobuf:"varint,3,opt,name=bytes_recv,json=bytesRecv,proto3" json:"bytes_recv,omitempty"`       // Total bytes received
	PacketsSent   uint64                 `protobuf:"varint,4,opt,name=packets_sent,json=packetsSent,proto3" json:"packets_sent,omitempty"` // Total packets sent
	PacketsRecv   uint64                 `protobuf:"varint,5,opt,name=packets_recv,json=packetsRecv,proto3" json:"packets_recv,omitempty"` // Total packets received
	ErrorsIn      uint64                 `protobuf:"varint,6,opt,name=errors_in,json=errorsIn,proto3" json:"errors_in,omitempty"`          // Input errors
	ErrorsOut     uint64                 `protobuf:"varint,7,opt,name=errors_out,json=errorsOut,proto3" json:"errors_out,omitempty"`       // Output errors
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkMetrics) Reset() {
	*x = NetworkMetrics{}
	mi := &file_croupier_ops_v1_ops_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkMetrics) ProtoMessage() {}

func (x *NetworkMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_croupier_ops_v1_ops_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkMetrics.ProtoReflect.Descriptor instead.
func (*NetworkMetrics) Descriptor() ([]byte, []int) {
	return file_croupier_ops_v1_ops_proto_rawDescGZIP(), []int{4}
}

func (x *NetworkMetrics) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

func (x *NetworkMetrics) GetBytesSent() uint64 {
	if x != nil {
		return x.BytesSent
	}
	return 0
}

func (x *NetworkMetrics) GetBytesRecv() uint64 {
	if x != nil {
		return x.BytesRecv
	}
	return 0
}

func (x *NetworkMetrics) GetPacketsSent() uint64 {
	if x != nil {
		return x.PacketsSent
	}
	return 0
}

func (x *NetworkMetrics) GetPacketsRecv() uint64 {
	if x != nil {
		return x.PacketsRecv
	}
	return 0
}

func (x *NetworkMetrics) GetErrorsIn() uint64 {
	if x != nil {
		return x.ErrorsIn
	}
	return 0
}

func (x *NetworkMetrics) GetErrorsOut() uint64 {
	if x != nil {
		return x.ErrorsOut
	}
	return 0
}

type ProcessMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           int32                  `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`                                    // Process ID
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                   // Process name
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`                               // Process status
	CpuPercent    float64                `protobuf:"fixed64,4,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`   // CPU usage percentage
	MemoryBytes   uint64                 `protobuf:"varint,5,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"` // Memory usage in bytes
	Threads       int32                  `protobuf:"varint,6,opt,name=threads,proto3" json:"threads,omitempty"`                            // Number of threads
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`        // Process start time
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessMetrics) Reset() {
	*x = ProcessMetrics{}
	mi := &file_croupier_ops_v1_ops_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessMetrics) ProtoMessage() {}

func (x *ProcessMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_croupier_ops_v1_ops_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessMetrics.ProtoReflect.Descriptor instead.
func (*ProcessMetrics) Descriptor() ([]byte, []int) {
	return file_croupier_ops_v1_ops_proto_rawDescGZIP(), []int{5}
}

func (x *ProcessMetrics) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ProcessMetrics) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProcessMetrics) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ProcessMetrics) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *ProcessMetrics) GetMemoryBytes() uint64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *ProcessMetrics) GetThreads() int32 {
	if x != nil {
		return x.Threads
	}
	return 0
}

func (x *ProcessMetrics) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

// SystemInfo contains detailed system information.
type SystemInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Os            string                 `protobuf:"bytes,2,opt,name=os,proto3" json:"os,omitempty"`                                            // Operating system (linux, windows, darwin)
	OsVersion     string                 `protobuf:"bytes,3,opt,name=os_version,json=osVersion,proto3" json:"os_version,omitempty"`             // OS version
	KernelVersion string                 `protobuf:"bytes,4,opt,name=kernel_version,json=kernelVersion,proto3" json:"kernel_version,omitempty"` // Kernel version
	Arch          string                 `protobuf:"bytes,5,opt,name=arch,proto3" json:"arch,omitempty"`                                        // Architecture (amd64, arm64, etc.)
	CpuCores      int32                  `protobuf:"varint,6,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`               // Number of CPU cores
	TotalMemory   uint64                 `protobuf:"varint,7,opt,name=total_memory,json=totalMemory,proto3" json:"total_memory,omitempty"`      // Total memory in bytes
	BootTime      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=boot_time,json=bootTime,proto3" json:"boot_time,omitempty"`                // System boot time
	AgentVersion  string                 `protobuf:"bytes,9,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`    // Croupier agent version
	// Ops module status
	OpsStatus     *OpsStatus `protobuf:"bytes,10,opt,name=ops_status,json=opsStatus,proto3" json:"ops_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemInfo) Reset() {
	*x = SystemInfo{}
	mi := &file_croupier_ops_v1_ops_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemInfo) ProtoMessage() {}

func (x *SystemInfo) ProtoReflect() protoreflect.Message {
	mi := &file_croupier_ops_v1_ops_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemInfo.ProtoReflect.Descriptor instead.
func (*SystemInfo) Descriptor() ([]byte, []int) {
	return file_croupier_ops_v1_ops_proto_rawDescGZIP(), []int{6}
}

func (x *SystemInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *SystemInfo) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *SystemInfo) GetOsVersion() string {
	if x != nil {
		return x.OsVersion
	}
	return ""
}

func (x *SystemInfo) GetKernelVersion() string {
	if x != nil {
		return x.KernelVersion
	}
	return ""
}

func (x *SystemInfo) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *SystemInfo) GetCpuCores() int32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *SystemInfo) GetTotalMemory() uint64 {
	if x != nil {
		return x.TotalMemory
	}
	return 0
}

func (x *SystemInfo) GetBootTime() *timestamppb.Timestamp {
	if x != nil {
		return x.BootTime
	}
	return nil
}

func (x *SystemInfo) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *SystemInfo) GetOpsStatus() *OpsStatus {
	if x != nil {
		return x.OpsStatus
	}
	return nil
}

type OpsStatus struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Enabled          bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`                                          // Whether ops module is enabled
	AllowRestart     bool                   `protobuf:"varint,2,opt,name=allow_restart,json=allowRestart,proto3" json:"allow_restart,omitempty"`            // Whether restart operations are allowed
	AllowExec        bool                   `protobuf:"varint,3,opt,name=allow_exec,json=allowExec,proto3" json:"allow_exec,omitempty"`                     // Whether command execution is allowed
	ManagedProcesses []string               `protobuf:"bytes,4,rep,name=managed_processes,json=managedProcesses,proto3" json:"managed_processes,omitempty"` // List of managed process names
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *OpsStatus) Reset() {
	*x = OpsStatus{}
	mi := &file_croupier_ops_v1_ops_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpsStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpsStatus) ProtoMessage() {}

func (x *OpsStatus) ProtoReflect() protoreflect.Message {
	mi := &file_croupier_ops_v1_ops_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpsStatus.ProtoReflect.Descriptor instead.
func (*OpsStatus) Descriptor() ([]byte, []int) {
	return file_croupier_ops_v1_ops_proto_rawDescGZIP(), []int{7}
}

func (x *OpsStatus) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *OpsStatus) GetAllowRestart() bool {
	if x != nil {
		return x.AllowRestart
	}
	return false
}

func (x *OpsStatus) GetAllowExec() bool {
	if x != nil {
		return x.AllowExec
	}
	return false
}

func (x *OpsStatus) GetManagedProcesses() []string {
	if x != nil {
		return x.ManagedProcesses
	}
	return nil
}

// RestartProcessRequest requests a process restart.
type RestartProcessRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProcessName    string                 `protobuf:"bytes,1,opt,name=process_name,json=processName,proto3" json:"process_name,omitempty"`           // Name of the process to restart
	Force          bool                   `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`                                         // Force restart (kill if not responding)
	TimeoutSeconds int32                  `protobuf:"varint,3,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"` // Timeout for graceful shutdown (default: 30)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RestartProcessRequest) Reset() {
	*x = RestartProcessRequest{}
	mi := &file_croupier_ops_v1_ops_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartProcessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartProcessRequest) ProtoMessage() {}

func (x *RestartProcessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_croupier_ops_v1_ops_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartProcessRequest.ProtoReflect.Descriptor instead.
func (*RestartProcessRequest) Descriptor() ([]byte, []int) {
	return file_croupier_ops_v1_ops_proto_rawDescGZIP(), []int{8}
}

func (x *RestartProcessRequest) GetProcessName() string {
	if x != nil {
		return x.ProcessName
	}
	return ""
}

func (x *RestartProcessRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

func (x *RestartProcessRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type RestartProcessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	NewPid        int32                  `protobuf:"varint,3,opt,name=new_pid,json=newPid,proto3" json:"new_pid,omitempty"` // New process ID after restart
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestartProcessResponse) Reset() {
	*x = RestartProcessResponse{}
	mi := &file_croupier_ops_v1_ops_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartProcessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartProcessResponse) ProtoMessage() {}

func (x *RestartProcessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_croupier_ops_v1_ops_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartProcessResponse.ProtoReflect.Descriptor instead.
func (*RestartProcessResponse) Descriptor() ([]byte, []int) {
	return file_croupier_ops_v1_ops_proto_rawDescGZIP(), []int{9}
}

func (x *RestartProcessResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RestartProcessResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RestartProcessResponse) GetNewPid() int32 {
	if x != nil {
		return x.NewPid
	}
	return 0
}

// StopProcessRequest requests a process stop.
type StopProcessRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProcessName    string                 `protobuf:"bytes,1,opt,name=process_name,json=processName,proto3" json:"process_name,omitempty"`           // Name of the process to stop
	Force          bool                   `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`                                         // Force stop (SIGKILL instead of SIGTERM)
	TimeoutSeconds int32                  `protobuf:"varint,3,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"` // Timeout for graceful shutdown
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StopProcessRequest) Reset() {
	*x = StopProcessRequest{}
	mi := &file_croupier_ops_v1_ops_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopProcessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopProcessRequest) ProtoMessage() {}

func (x *StopProcessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_croupier_ops_v1_ops_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopProcessRequest.ProtoReflect.Descriptor instead.
func (*StopProcessRequest) Descriptor() ([]byte, []int) {
	return file_croupier_ops_v1_ops_proto_rawDescGZIP(), []int{10}
}

func (x *StopProcessRequest) GetProcessName() string {
	if x != nil {
		return x.ProcessName
	}
	return ""
}

func (x *StopProcessRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

func (x *StopProcessRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type StopProcessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopProcessResponse) Reset() {
	*x = StopProcessResponse{}
	mi := &file_croupier_ops_v1_ops_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopProcessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopProcessResponse) ProtoMessage() {}

func (x *StopProcessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_croupier_ops_v1_ops_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopProcessResponse.ProtoReflect.Descriptor instead.
func (*StopProcessResponse) Descriptor() ([]byte, []int) {
	return file_croupier_ops_v1_ops_proto_rawDescGZIP(), []int{11}
}

func (x *StopProcessResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StopProcessResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// StartProcessRequest requests a process start.
type StartProcessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProcessName   string                 `protobuf:"bytes,1,opt,name=process_name,json=processName,proto3" json:"process_name,omitempty"` // Name of the process to start
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartProcessRequest) Reset() {
	*x = StartProcessRequest{}
	mi := &file_croupier_ops_v1_ops_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartProcessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartProcessRequest) ProtoMessage() {}

func (x *StartProcessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_croupier_ops_v1_ops_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartProcessRequest.ProtoReflect.Descriptor instead.
func (*StartProcessRequest) Descriptor() ([]byte, []int) {
	return file_croupier_ops_v1_ops_proto_rawDescGZIP(), []int{12}
}

func (x *StartProcessRequest) GetProcessName() string {
	if x != nil {
		return x.ProcessName
	}
	return ""
}

type StartProcessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Pid           int32                  `protobuf:"varint,3,opt,name=pid,proto3" json:"pid,omitempty"` // Process ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartProcessResponse) Reset() {
	*x = StartProcessResponse{}
	mi := &file_croupier_ops_v1_ops_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartProcessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartProcessResponse) ProtoMessage() {}

func (x *StartProcessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_croupier_ops_v1_ops_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartProcessResponse.ProtoReflect.Descriptor instead.
func (*StartProcessResponse) Descriptor() ([]byte, []int) {
	return file_croupier_ops_v1_ops_proto_rawDescGZIP(), []int{13}
}

func (x *StartProcessResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StartProcessResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StartProcessResponse) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

// ListProcessesResponse contains the list of managed processes.
type ListProcessesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Processes     []*ManagedProcess      `protobuf:"bytes,1,rep,name=processes,proto3" json:"processes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProcessesResponse) Reset() {
	*x = ListProcessesResponse{}
	mi := &file_croupier_ops_v1_ops_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProcessesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProcessesResponse) ProtoMessage() {}

func (x *ListProcessesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_croupier_ops_v1_ops_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProcessesResponse.ProtoReflect.Descriptor instead.
func (*ListProcessesResponse) Descriptor() ([]byte, []int) {
	return file_croupier_ops_v1_ops_proto_rawDescGZIP(), []int{14}
}

func (x *ListProcessesResponse) GetProcesses() []*ManagedProcess {
	if x != nil {
		return x.Processes
	}
	return nil
}

type ManagedProcess struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                      // Process name (as configured)
	Command       string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`                                // Command to start the process
	WorkingDir    string                 `protobuf:"bytes,3,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"`        // Working directory
	State         ProcessState           `protobuf:"varint,4,opt,name=state,proto3,enum=croupier.ops.v1.ProcessState" json:"state,omitempty"` // Current state
	Pid           int32                  `protobuf:"varint,5,opt,name=pid,proto3" json:"pid,omitempty"`                                       // Current PID (0 if not running)
	RestartCount  int32                  `protobuf:"varint,6,opt,name=restart_count,json=restartCount,proto3" json:"restart_count,omitempty"` // Number of restarts
	LastStart     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=last_start,json=lastStart,proto3" json:"last_start,omitempty"`           // Last start time
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManagedProcess) Reset() {
	*x = ManagedProcess{}
	mi := &file_croupier_ops_v1_ops_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManagedProcess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagedProcess) ProtoMessage() {}

func (x *ManagedProcess) ProtoReflect() protoreflect.Message {
	mi := &file_croupier_ops_v1_ops_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagedProcess.ProtoReflect.Descriptor instead.
func (*ManagedProcess) Descriptor() ([]byte, []int) {
	return file_croupier_ops_v1_ops_proto_rawDescGZIP(), []int{15}
}

func (x *ManagedProcess) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ManagedProcess) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ManagedProcess) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

func (x *ManagedProcess) GetState() ProcessState {
	if x != nil {
		return x.State
	}
	return ProcessState_PROCESS_STATE_UNSPECIFIED
}

func (x *ManagedProcess) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ManagedProcess) GetRestartCount() int32 {
	if x != nil {
		return x.RestartCount
	}
	return 0
}

func (x *ManagedProcess) GetLastStart() *timestamppb.Timestamp {
	if x != nil {
		return x.LastStart
	}
	return nil
}

// ExecuteCommandRequest requests command execution.
// WARNING: This is a high-risk operation.
type ExecuteCommandRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Command        string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`                                                                   // Command to execute
	Args           []string               `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`                                                                         // Command arguments
	WorkingDir     string                 `protobuf:"bytes,3,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"`                                           // Working directory (optional)
	Env            map[string]string      `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Environment variables (optional)
	TimeoutSeconds int32                  `protobuf:"varint,5,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`                              // Execution timeout (default: 60, max: 300)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExecuteCommandRequest) Reset() {
	*x = ExecuteCommandRequest{}
	mi := &file_croupier_ops_v1_ops_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteCommandRequest) ProtoMessage() {}

func (x *ExecuteCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_croupier_ops_v1_ops_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteCommandRequest.ProtoReflect.Descriptor instead.
func (*ExecuteCommandRequest) Descriptor() ([]byte, []int) {
	return file_croupier_ops_v1_ops_proto_rawDescGZIP(), []int{16}
}

func (x *ExecuteCommandRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ExecuteCommandRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ExecuteCommandRequest) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

func (x *ExecuteCommandRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *ExecuteCommandRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type ExecuteCommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ExitCode      int32                  `protobuf:"varint,2,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	StdOut        string                 `protobuf:"bytes,3,opt,name=std_out,json=stdOut,proto3" json:"std_out,omitempty"` // Renamed from 'stdout' to avoid Windows CRT macro conflict
	StdErr        string                 `protobuf:"bytes,4,opt,name=std_err,json=stdErr,proto3" json:"std_err,omitempty"` // Renamed from 'stderr' to avoid Windows CRT macro conflict
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`                 // Error message if execution failed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteCommandResponse) Reset() {
	*x = ExecuteCommandResponse{}
	mi := &file_croupier_ops_v1_ops_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteCommandResponse) ProtoMessage() {}

func (x *ExecuteCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_croupier_ops_v1_ops_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteCommandResponse.ProtoReflect.Descriptor instead.
func (*ExecuteCommandResponse) Descriptor() ([]byte, []int) {
	return file_croupier_ops_v1_ops_proto_rawDescGZIP(), []int{17}
}

func (x *ExecuteCommandResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ExecuteCommandResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ExecuteCommandResponse) GetStdOut() string {
	if x != nil {
		return x.StdOut
	}
	return ""
}

func (x *ExecuteCommandResponse) GetStdErr() string {
	if x != nil {
		return x.StdErr
	}
	return ""
}

func (x *ExecuteCommandResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// ListServicesRequest requests a list of system services.
type ListServicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         string                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`                                // Filter by state: "running", "stopped", "paused" (optional)
	NamePattern   string                 `protobuf:"bytes,2,opt,name=name_pattern,json=namePattern,proto3" json:"name_pattern,omitempty"` // Filter by service name pattern (optional)
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`                               // Maximum number of results (default: 100)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServicesRequest) Reset() {
	*x = ListServicesRequest{}
	mi := &file_croupier_ops_v1_ops_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServicesRequest) ProtoMessage() {}

func (x *ListServicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_croupier_ops_v1_ops_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServicesRequest.ProtoReflect.Descriptor instead.
func (*ListServicesRequest) Descriptor() ([]byte, []int) {
	return file_croupier_ops_v1_ops_proto_rawDescGZIP(), []int{18}
}

func (x *ListServicesRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ListServicesRequest) GetNamePattern() string {
	if x != nil {
		return x.NamePattern
	}
	return ""
}

func (x *ListServicesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// ListServicesResponse contains the list of system services.
type ListServicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Services      []*ServiceInfo         `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServicesResponse) Reset() {
	*x = ListServicesResponse{}
	mi := &file_croupier_ops_v1_ops_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServicesResponse) ProtoMessage() {}

func (x *ListServicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_croupier_ops_v1_ops_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServicesResponse.ProtoReflect.Descriptor instead.
func (*ListServicesResponse) Descriptor() ([]byte, []int) {
	return file_croupier_ops_v1_ops_proto_rawDescGZIP(), []int{19}
}

func (x *ListServicesResponse) GetServices() []*ServiceInfo {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *ListServicesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// ServiceInfo contains information about a system service.
type ServiceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                  // Service name
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"` // Display name
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`                              // Status: "running", "stopped", "paused"
	StartType     string                 `protobuf:"bytes,4,opt,name=start_type,json=startType,proto3" json:"start_type,omitempty"`       // Start type: "auto", "manual", "disabled"
	ProcessId     uint32                 `protobuf:"varint,5,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`      // Process ID (0 if not running)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceInfo) Reset() {
	*x = ServiceInfo{}
	mi := &file_croupier_ops_v1_ops_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceInfo) ProtoMessage() {}

func (x *ServiceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_croupier_ops_v1_ops_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceInfo.ProtoReflect.Descriptor instead.
func (*ServiceInfo) Descriptor() ([]byte, []int) {
	return file_croupier_ops_v1_ops_proto_rawDescGZIP(), []int{20}
}

func (x *ServiceInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceInfo) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *ServiceInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ServiceInfo) GetStartType() string {
	if x != nil {
		return x.StartType
	}
	return ""
}

func (x *ServiceInfo) GetProcessId() uint32 {
	if x != nil {
		return x.ProcessId
	}
	return 0
}

// GetServiceStatusRequest requests detailed status of a specific service.
type GetServiceStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // Service name
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServiceStatusRequest) Reset() {
	*x = GetServiceStatusRequest{}
	mi := &file_croupier_ops_v1_ops_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServiceStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceStatusRequest) ProtoMessage() {}

func (x *GetServiceStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_croupier_ops_v1_ops_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceStatusRequest.ProtoReflect.Descriptor instead.
func (*GetServiceStatusRequest) Descriptor() ([]byte, []int) {
	return file_croupier_ops_v1_ops_proto_rawDescGZIP(), []int{21}
}

func (x *GetServiceStatusRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// GetServiceStatusResponse contains detailed service status.
type GetServiceStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                  // Service name
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"` // Display name
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`                              // Status
	StartType     string                 `protobuf:"bytes,4,opt,name=start_type,json=startType,proto3" json:"start_type,omitempty"`       // Start type
	ProcessId     uint32                 `protobuf:"varint,5,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`      // Process ID (0 if not running)
	BinaryPath    string                 `protobuf:"bytes,6,opt,name=binary_path,json=binaryPath,proto3" json:"binary_path,omitempty"`    // Path to service binary
	Description   string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`                    // Service description
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServiceStatusResponse) Reset() {
	*x = GetServiceStatusResponse{}
	mi := &file_croupier_ops_v1_ops_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServiceStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceStatusResponse) ProtoMessage() {}

func (x *GetServiceStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_croupier_ops_v1_ops_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceStatusResponse.ProtoReflect.Descriptor instead.
func (*GetServiceStatusResponse) Descriptor() ([]byte, []int) {
	return file_croupier_ops_v1_ops_proto_rawDescGZIP(), []int{22}
}

func (x *GetServiceStatusResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetServiceStatusResponse) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *GetServiceStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetServiceStatusResponse) GetStartType() string {
	if x != nil {
		return x.StartType
	}
	return ""
}

func (x *GetServiceStatusResponse) GetProcessId() uint32 {
	if x != nil {
		return x.ProcessId
	}
	return 0
}

func (x *GetServiceStatusResponse) GetBinaryPath() string {
	if x != nil {
		return x.BinaryPath
	}
	return ""
}

func (x *GetServiceStatusResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// ListCronJobsResponse contains the list of cron jobs.
type ListCronJobsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jobs          []*CronJob             `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCronJobsResponse) Reset() {
	*x = ListCronJobsResponse{}
	mi := &file_croupier_ops_v1_ops_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCronJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCronJobsResponse) ProtoMessage() {}

func (x *ListCronJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_croupier_ops_v1_ops_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCronJobsResponse.ProtoReflect.Descriptor instead.
func (*ListCronJobsResponse) Descriptor() ([]byte, []int) {
	return file_croupier_ops_v1_ops_proto_rawDescGZIP(), []int{23}
}

func (x *ListCronJobsResponse) GetJobs() []*CronJob {
	if x != nil {
		return x.Jobs
	}
	return nil
}

func (x *ListCronJobsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// CronJob represents a cron job entry.
type CronJob struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schedule      string                 `protobuf:"bytes,1,opt,name=schedule,proto3" json:"schedule,omitempty"`                       // Cron expression or @keyword
	Command       string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`                         // Command to execute
	User          string                 `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`                               // User who runs the job
	SourceFile    string                 `protobuf:"bytes,4,opt,name=source_file,json=sourceFile,proto3" json:"source_file,omitempty"` // File where this job is defined
	Enabled       bool                   `protobuf:"varint,5,opt,name=enabled,proto3" json:"enabled,omitempty"`                        // Whether the job is active
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CronJob) Reset() {
	*x = CronJob{}
	mi := &file_croupier_ops_v1_ops_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CronJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CronJob) ProtoMessage() {}

func (x *CronJob) ProtoReflect() protoreflect.Message {
	mi := &file_croupier_ops_v1_ops_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CronJob.ProtoReflect.Descriptor instead.
func (*CronJob) Descriptor() ([]byte, []int) {
	return file_croupier_ops_v1_ops_proto_rawDescGZIP(), []int{24}
}

func (x *CronJob) GetSchedule() string {
	if x != nil {
		return x.Schedule
	}
	return ""
}

func (x *CronJob) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *CronJob) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *CronJob) GetSourceFile() string {
	if x != nil {
		return x.SourceFile
	}
	return ""
}

func (x *CronJob) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

var File_croupier_ops_v1_ops_proto protoreflect.FileDescriptor

const file_croupier_ops_v1_ops_proto_rawDesc = "" +
	"\n" +
	"\x19croupier/ops/v1/ops.proto\x12\x0fcroupier.ops.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xfa\x03\n" +
	"\rMetricsReport\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12-\n" +
	"\x03cpu\x18\x03 \x01(\v2\x1b.croupier.ops.v1.CpuMetricsR\x03cpu\x126\n" +
	"\x06memory\x18\x04 \x01(\v2\x1e.croupier.ops.v1.MemoryMetricsR\x06memory\x122\n" +
	"\x05disks\x18\x05 \x03(\v2\x1c.croupier.ops.v1.DiskMetricsR\x05disks\x12;\n" +
	"\bnetworks\x18\x06 \x03(\v2\x1f.croupier.ops.v1.NetworkMetricsR\bnetworks\x12=\n" +
	"\tprocesses\x18\a \x03(\v2\x1f.croupier.ops.v1.ProcessMetricsR\tprocesses\x12B\n" +
	"\x06custom\x18\b \x03(\v2*.croupier.ops.v1.MetricsReport.CustomEntryR\x06custom\x1a9\n" +
	"\vCustomEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"\xaf\x01\n" +
	"\n" +
	"CpuMetrics\x12#\n" +
	"\rusage_percent\x18\x01 \x01(\x01R\fusagePercent\x12\x14\n" +
	"\x05cores\x18\x02 \x01(\x05R\x05cores\x12\x19\n" +
	"\bper_core\x18\x03 \x03(\x01R\aperCore\x12\x17\n" +
	"\aload_1m\x18\x04 \x01(\x01R\x06load1m\x12\x17\n" +
	"\aload_5m\x18\x05 \x01(\x01R\x06load5m\x12\x19\n" +
	"\bload_15m\x18\x06 \x01(\x01R\aload15m\"\xd9\x01\n" +
	"\rMemoryMetrics\x12\x1f\n" +
	"\vtotal_bytes\x18\x01 \x01(\x04R\n" +
	"totalBytes\x12\x1d\n" +
	"\n" +
	"used_bytes\x18\x02 \x01(\x04R\tusedBytes\x12'\n" +
	"\x0favailable_bytes\x18\x03 \x01(\x04R\x0eavailableBytes\x12#\n" +
	"\rusage_percent\x18\x04 \x01(\x01R\fusagePercent\x12\x1d\n" +
	"\n" +
	"swap_total\x18\x05 \x01(\x04R\tswapTotal\x12\x1b\n" +
	"\tswap_used\x18\x06 \x01(\x04R\bswapUsed\"\xad\x02\n" +
	"\vDiskMetrics\x12\x1f\n" +
	"\vmount_point\x18\x01 \x01(\tR\n" +
	"mountPoint\x12\x16\n" +
	"\x06device\x18\x02 \x01(\tR\x06device\x12\x17\n" +
	"\afs_type\x18\x03 \x01(\tR\x06fsType\x12\x1f\n" +
	"\vtotal_bytes\x18\x04 \x01(\x04R\n" +
	"totalBytes\x12\x1d\n" +
	"\n" +
	"used_bytes\x18\x05 \x01(\x04R\tusedBytes\x12'\n" +
	"\x0favailable_bytes\x18\x06 \x01(\x04R\x0eavailableBytes\x12#\n" +
	"\rusage_percent\x18\a \x01(\x01R\fusagePercent\x12\x1f\n" +
	"\vinode_total\x18\b \x01(\x04R\n" +
	"inodeTotal\x12\x1d\n" +
	"\n" +
	"inode_used\x18\t \x01(\x04R\tinodeUsed\"\xee\x01\n" +
	"\x0eNetworkMetrics\x12\x1c\n" +
	"\tinterface\x18\x01 \x01(\tR\tinterface\x12\x1d\n" +
	"\n" +
	"bytes_sent\x18\x02 \x01(\x04R\tbytesSent\x12\x1d\n" +
	"\n" +
	"bytes_recv\x18\x03 \x01(\x04R\tbytesRecv\x12!\n" +
	"\fpackets_sent\x18\x04 \x01(\x04R\vpacketsSent\x12!\n" +
	"\fpackets_recv\x18\x05 \x01(\x04R\vpacketsRecv\x12\x1b\n" +
	"\terrors_in\x18\x06 \x01(\x04R\berrorsIn\x12\x1d\n" +
	"\n" +
	"errors_out\x18\a \x01(\x04R\terrorsOut\"\xe7\x01\n" +
	"\x0eProcessMetrics\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1f\n" +
	"\vcpu_percent\x18\x04 \x01(\x01R\n" +
	"cpuPercent\x12!\n" +
	"\fmemory_bytes\x18\x05 \x01(\x04R\vmemoryBytes\x12\x18\n" +
	"\athreads\x18\x06 \x01(\x05R\athreads\x129\n" +
	"\n" +
	"start_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\"\xeb\x02\n" +
	"\n" +
	"SystemInfo\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02os\x18\x02 \x01(\tR\x02os\x12\x1d\n" +
	"\n" +
	"os_version\x18\x03 \x01(\tR\tosVersion\x12%\n" +
	"\x0ekernel_version\x18\x04 \x01(\tR\rkernelVersion\x12\x12\n" +
	"\x04arch\x18\x05 \x01(\tR\x04arch\x12\x1b\n" +
	"\tcpu_cores\x18\x06 \x01(\x05R\bcpuCores\x12!\n" +
	"\ftotal_memory\x18\a \x01(\x04R\vtotalMemory\x127\n" +
	"\tboot_time\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\bbootTime\x12#\n" +
	"\ragent_version\x18\t \x01(\tR\fagentVersion\x129\n" +
	"\n" +
	"ops_status\x18\n" +
	" \x01(\v2\x1a.croupier.ops.v1.OpsStatusR\topsStatus\"\x96\x01\n" +
	"\tOpsStatus\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12#\n" +
	"\rallow_restart\x18\x02 \x01(\bR\fallowRestart\x12\x1d\n" +
	"\n" +
	"allow_exec\x18\x03 \x01(\bR\tallowExec\x12+\n" +
	"\x11managed_processes\x18\x04 \x03(\tR\x10managedProcesses\"y\n" +
	"\x15RestartProcessRequest\x12!\n" +
	"\fprocess_name\x18\x01 \x01(\tR\vprocessName\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\x12'\n" +
	"\x0ftimeout_seconds\x18\x03 \x01(\x05R\x0etimeoutSeconds\"e\n" +
	"\x16RestartProcessResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x17\n" +
	"\anew_pid\x18\x03 \x01(\x05R\x06newPid\"v\n" +
	"\x12StopProcessRequest\x12!\n" +
	"\fprocess_name\x18\x01 \x01(\tR\vprocessName\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\x12'\n" +
	"\x0ftimeout_seconds\x18\x03 \x01(\x05R\x0etimeoutSeconds\"I\n" +
	"\x13StopProcessResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"8\n" +
	"\x13StartProcessRequest\x12!\n" +
	"\fprocess_name\x18\x01 \x01(\tR\vprocessName\"\\\n" +
	"\x14StartProcessResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x10\n" +
	"\x03pid\x18\x03 \x01(\x05R\x03pid\"V\n" +
	"\x15ListProcessesResponse\x12=\n" +
	"\tprocesses\x18\x01 \x03(\v2\x1f.croupier.ops.v1.ManagedProcessR\tprocesses\"\x86\x02\n" +
	"\x0eManagedProcess\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x12\x1f\n" +
	"\vworking_dir\x18\x03 \x01(\tR\n" +
	"workingDir\x123\n" +
	"\x05state\x18\x04 \x01(\x0e2\x1d.croupier.ops.v1.ProcessStateR\x05state\x12\x10\n" +
	"\x03pid\x18\x05 \x01(\x05R\x03pid\x12#\n" +
	"\rrestart_count\x18\x06 \x01(\x05R\frestartCount\x129\n" +
	"\n" +
	"last_start\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tlastStart\"\x8a\x02\n" +
	"\x15ExecuteCommandRequest\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x02 \x03(\tR\x04args\x12\x1f\n" +
	"\vworking_dir\x18\x03 \x01(\tR\n" +
	"workingDir\x12A\n" +
	"\x03env\x18\x04 \x03(\v2/.croupier.ops.v1.ExecuteCommandRequest.EnvEntryR\x03env\x12'\n" +
	"\x0ftimeout_seconds\x18\x05 \x01(\x05R\x0etimeoutSeconds\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x97\x01\n" +
	"\x16ExecuteCommandResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1b\n" +
	"\texit_code\x18\x02 \x01(\x05R\bexitCode\x12\x17\n" +
	"\astd_out\x18\x03 \x01(\tR\x06stdOut\x12\x17\n" +
	"\astd_err\x18\x04 \x01(\tR\x06stdErr\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"d\n" +
	"\x13ListServicesRequest\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\x12!\n" +
	"\fname_pattern\x18\x02 \x01(\tR\vnamePattern\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"f\n" +
	"\x14ListServicesResponse\x128\n" +
	"\bservices\x18\x01 \x03(\v2\x1c.croupier.ops.v1.ServiceInfoR\bservices\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\x9a\x01\n" +
	"\vServiceInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"start_type\x18\x04 \x01(\tR\tstartType\x12\x1d\n" +
	"\n" +
	"process_id\x18\x05 \x01(\rR\tprocessId\"-\n" +
	"\x17GetServiceStatusRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\xea\x01\n" +
	"\x18GetServiceStatusResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"start_type\x18\x04 \x01(\tR\tstartType\x12\x1d\n" +
	"\n" +
	"process_id\x18\x05 \x01(\rR\tprocessId\x12\x1f\n" +
	"\vbinary_path\x18\x06 \x01(\tR\n" +
	"binaryPath\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\"Z\n" +
	"\x14ListCronJobsResponse\x12,\n" +
	"\x04jobs\x18\x01 \x03(\v2\x18.croupier.ops.v1.CronJobR\x04jobs\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\x8e\x01\n" +
	"\aCronJob\x12\x1a\n" +
	"\bschedule\x18\x01 \x01(\tR\bschedule\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x12\x12\n" +
	"\x04user\x18\x03 \x01(\tR\x04user\x12\x1f\n" +
	"\vsource_file\x18\x04 \x01(\tR\n" +
	"sourceFile\x12\x18\n" +
	"\aenabled\x18\x05 \x01(\bR\aenabled*\xb5\x01\n" +
	"\fProcessState\x12\x1d\n" +
	"\x19PROCESS_STATE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15PROCESS_STATE_RUNNING\x10\x01\x12\x19\n" +
	"\x15PROCESS_STATE_STOPPED\x10\x02\x12\x18\n" +
	"\x14PROCESS_STATE_FAILED\x10\x03\x12\x1a\n" +
	"\x16PROCESS_STATE_STARTING\x10\x04\x12\x1a\n" +
	"\x16PROCESS_STATE_STOPPING\x10\x05Bj\n" +
	"\"io.github.cuihairu.croupier.ops.v1P\x01Z0github.com/cuihairu/croupier/sdks/go/pkg/pb/ops/v1;opsv1\xaa\x02\x0fCroupier.Ops.V1b\x06proto3"

var (
	file_croupier_ops_v1_ops_proto_rawDescOnce sync.Once
	file_croupier_ops_v1_ops_proto_rawDescData []byte
)

func file_croupier_ops_v1_ops_proto_rawDescGZIP() []byte {
	file_croupier_ops_v1_ops_proto_rawDescOnce.Do(func() {
		file_croupier_ops_v1_ops_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_croupier_ops_v1_ops_proto_rawDesc), len(file_croupier_ops_v1_ops_proto_rawDesc)))
	})
	return file_croupier_ops_v1_ops_proto_rawDescData
}

var file_croupier_ops_v1_ops_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_croupier_ops_v1_ops_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_croupier_ops_v1_ops_proto_goTypes = []any{
	(ProcessState)(0),                // 0: croupier.ops.v1.ProcessState
	(*MetricsReport)(nil),            // 1: croupier.ops.v1.MetricsReport
	(*CpuMetrics)(nil),               // 2: croupier.ops.v1.CpuMetrics
	(*MemoryMetrics)(nil),            // 3: croupier.ops.v1.MemoryMetrics
	(*DiskMetrics)(nil),              // 4: croupier.ops.v1.DiskMetrics
	(*NetworkMetrics)(nil),           // 5: croupier.ops.v1.NetworkMetrics
	(*ProcessMetrics)(nil),           // 6: croupier.ops.v1.ProcessMetrics
	(*SystemInfo)(nil),               // 7: croupier.ops.v1.SystemInfo
	(*OpsStatus)(nil),                // 8: croupier.ops.v1.OpsStatus
	(*RestartProcessRequest)(nil),    // 9: croupier.ops.v1.RestartProcessRequest
	(*RestartProcessResponse)(nil),   // 10: croupier.ops.v1.RestartProcessResponse
	(*StopProcessRequest)(nil),       // 11: croupier.ops.v1.StopProcessRequest
	(*StopProcessResponse)(nil),      // 12: croupier.ops.v1.StopProcessResponse
	(*StartProcessRequest)(nil),      // 13: croupier.ops.v1.StartProcessRequest
	(*StartProcessResponse)(nil),     // 14: croupier.ops.v1.StartProcessResponse
	(*ListProcessesResponse)(nil),    // 15: croupier.ops.v1.ListProcessesResponse
	(*ManagedProcess)(nil),           // 16: croupier.ops.v1.ManagedProcess
	(*ExecuteCommandRequest)(nil),    // 17: croupier.ops.v1.ExecuteCommandRequest
	(*ExecuteCommandResponse)(nil),   // 18: croupier.ops.v1.ExecuteCommandResponse
	(*ListServicesRequest)(nil),      // 19: croupier.ops.v1.ListServicesRequest
	(*ListServicesResponse)(nil),     // 20: croupier.ops.v1.ListServicesResponse
	(*ServiceInfo)(nil),              // 21: croupier.ops.v1.ServiceInfo
	(*GetServiceStatusRequest)(nil),  // 22: croupier.ops.v1.GetServiceStatusRequest
	(*GetServiceStatusResponse)(nil), // 23: croupier.ops.v1.GetServiceStatusResponse
	(*ListCronJobsResponse)(nil),     // 24: croupier.ops.v1.ListCronJobsResponse
	(*CronJob)(nil),                  // 25: croupier.ops.v1.CronJob
	nil,                              // 26: croupier.ops.v1.MetricsReport.CustomEntry
	nil,                              // 27: croupier.ops.v1.ExecuteCommandRequest.EnvEntry
	(*timestamppb.Timestamp)(nil),    // 28: google.protobuf.Timestamp
}
var file_croupier_ops_v1_ops_proto_depIdxs = []int32{
	28, // 0: croupier.ops.v1.MetricsReport.timestamp:type_name -> google.protobuf.Timestamp
	2,  // 1: croupier.ops.v1.MetricsReport.cpu:type_name -> croupier.ops.v1.CpuMetrics
	3,  // 2: croupier.ops.v1.MetricsReport.memory:type_name -> croupier.ops.v1.MemoryMetrics
	4,  // 3: croupier.ops.v1.MetricsReport.disks:type_name -> croupier.ops.v1.DiskMetrics
	5,  // 4: croupier.ops.v1.MetricsReport.networks:type_name -> croupier.ops.v1.NetworkMetrics
	6,  // 5: croupier.ops.v1.MetricsReport.processes:type_name -> croupier.ops.v1.ProcessMetrics
	26, // 6: croupier.ops.v1.MetricsReport.custom:type_name -> croupier.ops.v1.MetricsReport.CustomEntry
	28, // 7: croupier.ops.v1.ProcessMetrics.start_time:type_name -> google.protobuf.Timestamp
	28, // 8: croupier.ops.v1.SystemInfo.boot_time:type_name -> google.protobuf.Timestamp
	8,  // 9: croupier.ops.v1.SystemInfo.ops_status:type_name -> croupier.ops.v1.OpsStatus
	16, // 10: croupier.ops.v1.ListProcessesResponse.processes:type_name -> croupier.ops.v1.ManagedProcess
	0,  // 11: croupier.ops.v1.ManagedProcess.state:type_name -> croupier.ops.v1.ProcessState
	28, // 12: croupier.ops.v1.ManagedProcess.last_start:type_name -> google.protobuf.Timestamp
	27, // 13: croupier.ops.v1.ExecuteCommandRequest.env:type_name -> croupier.ops.v1.ExecuteCommandRequest.EnvEntry
	21, // 14: croupier.ops.v1.ListServicesResponse.services:type_name -> croupier.ops.v1.ServiceInfo
	25, // 15: croupier.ops.v1.ListCronJobsResponse.jobs:type_name -> croupier.ops.v1.CronJob
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_croupier_ops_v1_ops_proto_init() }
func file_croupier_ops_v1_ops_proto_init() {
	if File_croupier_ops_v1_ops_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_croupier_ops_v1_ops_proto_rawDesc), len(file_croupier_ops_v1_ops_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_croupier_ops_v1_ops_proto_goTypes,
		DependencyIndexes: file_croupier_ops_v1_ops_proto_depIdxs,
		EnumInfos:         file_croupier_ops_v1_ops_proto_enumTypes,
		MessageInfos:      file_croupier_ops_v1_ops_proto_msgTypes,
	}.Build()
	File_croupier_ops_v1_ops_proto = out.File
	file_croupier_ops_v1_ops_proto_goTypes = nil
	file_croupier_ops_v1_ops_proto_depIdxs = nil
}
