// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: croupier/function/v1/function.proto

package functionv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	FunctionService_Invoke_FullMethodName    = "/croupier.function.v1.FunctionService/Invoke"
	FunctionService_StartJob_FullMethodName  = "/croupier.function.v1.FunctionService/StartJob"
	FunctionService_StreamJob_FullMethodName = "/croupier.function.v1.FunctionService/StreamJob"
	FunctionService_CancelJob_FullMethodName = "/croupier.function.v1.FunctionService/CancelJob"
)

// FunctionServiceClient is the client API for FunctionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FunctionServiceClient interface {
	Invoke(ctx context.Context, in *InvokeRequest, opts ...grpc.CallOption) (*InvokeResponse, error)
	StartJob(ctx context.Context, in *InvokeRequest, opts ...grpc.CallOption) (*StartJobResponse, error)
	StreamJob(ctx context.Context, in *JobStreamRequest, opts ...grpc.CallOption) (FunctionService_StreamJobClient, error)
	CancelJob(ctx context.Context, in *CancelJobRequest, opts ...grpc.CallOption) (*StartJobResponse, error)
}

type functionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFunctionServiceClient(cc grpc.ClientConnInterface) FunctionServiceClient {
	return &functionServiceClient{cc}
}

func (c *functionServiceClient) Invoke(ctx context.Context, in *InvokeRequest, opts ...grpc.CallOption) (*InvokeResponse, error) {
	out := new(InvokeResponse)
	err := c.cc.Invoke(ctx, FunctionService_Invoke_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *functionServiceClient) StartJob(ctx context.Context, in *InvokeRequest, opts ...grpc.CallOption) (*StartJobResponse, error) {
	out := new(StartJobResponse)
	err := c.cc.Invoke(ctx, FunctionService_StartJob_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *functionServiceClient) StreamJob(ctx context.Context, in *JobStreamRequest, opts ...grpc.CallOption) (FunctionService_StreamJobClient, error) {
	stream, err := c.cc.NewStream(ctx, &FunctionService_ServiceDesc.Streams[0], FunctionService_StreamJob_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &functionServiceStreamJobClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type FunctionService_StreamJobClient interface {
	Recv() (*JobEvent, error)
	grpc.ClientStream
}

type functionServiceStreamJobClient struct {
	grpc.ClientStream
}

func (x *functionServiceStreamJobClient) Recv() (*JobEvent, error) {
	m := new(JobEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *functionServiceClient) CancelJob(ctx context.Context, in *CancelJobRequest, opts ...grpc.CallOption) (*StartJobResponse, error) {
	out := new(StartJobResponse)
	err := c.cc.Invoke(ctx, FunctionService_CancelJob_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FunctionServiceServer is the server API for FunctionService service.
// All implementations must embed UnimplementedFunctionServiceServer
// for forward compatibility
type FunctionServiceServer interface {
	Invoke(context.Context, *InvokeRequest) (*InvokeResponse, error)
	StartJob(context.Context, *InvokeRequest) (*StartJobResponse, error)
	StreamJob(*JobStreamRequest, FunctionService_StreamJobServer) error
	CancelJob(context.Context, *CancelJobRequest) (*StartJobResponse, error)
	mustEmbedUnimplementedFunctionServiceServer()
}

// UnimplementedFunctionServiceServer must be embedded to have forward compatible implementations.
type UnimplementedFunctionServiceServer struct {
}

func (UnimplementedFunctionServiceServer) Invoke(context.Context, *InvokeRequest) (*InvokeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Invoke not implemented")
}
func (UnimplementedFunctionServiceServer) StartJob(context.Context, *InvokeRequest) (*StartJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartJob not implemented")
}
func (UnimplementedFunctionServiceServer) StreamJob(*JobStreamRequest, FunctionService_StreamJobServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamJob not implemented")
}
func (UnimplementedFunctionServiceServer) CancelJob(context.Context, *CancelJobRequest) (*StartJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelJob not implemented")
}
func (UnimplementedFunctionServiceServer) mustEmbedUnimplementedFunctionServiceServer() {}

// UnsafeFunctionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FunctionServiceServer will
// result in compilation errors.
type UnsafeFunctionServiceServer interface {
	mustEmbedUnimplementedFunctionServiceServer()
}

func RegisterFunctionServiceServer(s grpc.ServiceRegistrar, srv FunctionServiceServer) {
	s.RegisterService(&FunctionService_ServiceDesc, srv)
}

func _FunctionService_Invoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvokeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FunctionServiceServer).Invoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FunctionService_Invoke_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FunctionServiceServer).Invoke(ctx, req.(*InvokeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FunctionService_StartJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvokeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FunctionServiceServer).StartJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FunctionService_StartJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FunctionServiceServer).StartJob(ctx, req.(*InvokeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FunctionService_StreamJob_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(JobStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FunctionServiceServer).StreamJob(m, &functionServiceStreamJobServer{stream})
}

type FunctionService_StreamJobServer interface {
	Send(*JobEvent) error
	grpc.ServerStream
}

type functionServiceStreamJobServer struct {
	grpc.ServerStream
}

func (x *functionServiceStreamJobServer) Send(m *JobEvent) error {
	return x.ServerStream.SendMsg(m)
}

func _FunctionService_CancelJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FunctionServiceServer).CancelJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FunctionService_CancelJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FunctionServiceServer).CancelJob(ctx, req.(*CancelJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FunctionService_ServiceDesc is the grpc.ServiceDesc for FunctionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FunctionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "croupier.function.v1.FunctionService",
	HandlerType: (*FunctionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Invoke",
			Handler:    _FunctionService_Invoke_Handler,
		},
		{
			MethodName: "StartJob",
			Handler:    _FunctionService_StartJob_Handler,
		},
		{
			MethodName: "CancelJob",
			Handler:    _FunctionService_CancelJob_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamJob",
			Handler:       _FunctionService_StreamJob_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "croupier/function/v1/function.proto",
}
