// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: croupier/tunnel/v1/tunnel.proto

package tunnelv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	TunnelService_Open_FullMethodName = "/croupier.tunnel.v1.TunnelService/Open"
)

// TunnelServiceClient is the client API for TunnelService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TunnelServiceClient interface {
	Open(ctx context.Context, opts ...grpc.CallOption) (TunnelService_OpenClient, error)
}

type tunnelServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTunnelServiceClient(cc grpc.ClientConnInterface) TunnelServiceClient {
	return &tunnelServiceClient{cc}
}

func (c *tunnelServiceClient) Open(ctx context.Context, opts ...grpc.CallOption) (TunnelService_OpenClient, error) {
	stream, err := c.cc.NewStream(ctx, &TunnelService_ServiceDesc.Streams[0], TunnelService_Open_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &tunnelServiceOpenClient{stream}
	return x, nil
}

type TunnelService_OpenClient interface {
	Send(*TunnelMessage) error
	Recv() (*TunnelMessage, error)
	grpc.ClientStream
}

type tunnelServiceOpenClient struct {
	grpc.ClientStream
}

func (x *tunnelServiceOpenClient) Send(m *TunnelMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *tunnelServiceOpenClient) Recv() (*TunnelMessage, error) {
	m := new(TunnelMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TunnelServiceServer is the server API for TunnelService service.
// All implementations must embed UnimplementedTunnelServiceServer
// for forward compatibility
type TunnelServiceServer interface {
	Open(TunnelService_OpenServer) error
	mustEmbedUnimplementedTunnelServiceServer()
}

// UnimplementedTunnelServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTunnelServiceServer struct {
}

func (UnimplementedTunnelServiceServer) Open(TunnelService_OpenServer) error {
	return status.Errorf(codes.Unimplemented, "method Open not implemented")
}
func (UnimplementedTunnelServiceServer) mustEmbedUnimplementedTunnelServiceServer() {}

// UnsafeTunnelServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TunnelServiceServer will
// result in compilation errors.
type UnsafeTunnelServiceServer interface {
	mustEmbedUnimplementedTunnelServiceServer()
}

func RegisterTunnelServiceServer(s grpc.ServiceRegistrar, srv TunnelServiceServer) {
	s.RegisterService(&TunnelService_ServiceDesc, srv)
}

func _TunnelService_Open_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TunnelServiceServer).Open(&tunnelServiceOpenServer{stream})
}

type TunnelService_OpenServer interface {
	Send(*TunnelMessage) error
	Recv() (*TunnelMessage, error)
	grpc.ServerStream
}

type tunnelServiceOpenServer struct {
	grpc.ServerStream
}

func (x *tunnelServiceOpenServer) Send(m *TunnelMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *tunnelServiceOpenServer) Recv() (*TunnelMessage, error) {
	m := new(TunnelMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TunnelService_ServiceDesc is the grpc.ServiceDesc for TunnelService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TunnelService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "croupier.tunnel.v1.TunnelService",
	HandlerType: (*TunnelServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Open",
			Handler:       _TunnelService_Open_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "croupier/tunnel/v1/tunnel.proto",
}
