// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: croupier/agent/local/v1/local.proto

package localv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LocalControlService_RegisterLocal_FullMethodName = "/croupier.agent.local.v1.LocalControlService/RegisterLocal"
	LocalControlService_Heartbeat_FullMethodName     = "/croupier.agent.local.v1.LocalControlService/Heartbeat"
	LocalControlService_ListLocal_FullMethodName     = "/croupier.agent.local.v1.LocalControlService/ListLocal"
	LocalControlService_GetJobResult_FullMethodName  = "/croupier.agent.local.v1.LocalControlService/GetJobResult"
)

// LocalControlServiceClient is the client API for LocalControlService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LocalControlServiceClient interface {
	RegisterLocal(ctx context.Context, in *RegisterLocalRequest, opts ...grpc.CallOption) (*RegisterLocalResponse, error)
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	ListLocal(ctx context.Context, in *ListLocalRequest, opts ...grpc.CallOption) (*ListLocalResponse, error)
	GetJobResult(ctx context.Context, in *GetJobResultRequest, opts ...grpc.CallOption) (*GetJobResultResponse, error)
}

type localControlServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLocalControlServiceClient(cc grpc.ClientConnInterface) LocalControlServiceClient {
	return &localControlServiceClient{cc}
}

func (c *localControlServiceClient) RegisterLocal(ctx context.Context, in *RegisterLocalRequest, opts ...grpc.CallOption) (*RegisterLocalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterLocalResponse)
	err := c.cc.Invoke(ctx, LocalControlService_RegisterLocal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *localControlServiceClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, LocalControlService_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *localControlServiceClient) ListLocal(ctx context.Context, in *ListLocalRequest, opts ...grpc.CallOption) (*ListLocalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListLocalResponse)
	err := c.cc.Invoke(ctx, LocalControlService_ListLocal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *localControlServiceClient) GetJobResult(ctx context.Context, in *GetJobResultRequest, opts ...grpc.CallOption) (*GetJobResultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetJobResultResponse)
	err := c.cc.Invoke(ctx, LocalControlService_GetJobResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LocalControlServiceServer is the server API for LocalControlService service.
// All implementations must embed UnimplementedLocalControlServiceServer
// for forward compatibility.
type LocalControlServiceServer interface {
	RegisterLocal(context.Context, *RegisterLocalRequest) (*RegisterLocalResponse, error)
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	ListLocal(context.Context, *ListLocalRequest) (*ListLocalResponse, error)
	GetJobResult(context.Context, *GetJobResultRequest) (*GetJobResultResponse, error)
	mustEmbedUnimplementedLocalControlServiceServer()
}

// UnimplementedLocalControlServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLocalControlServiceServer struct{}

func (UnimplementedLocalControlServiceServer) RegisterLocal(context.Context, *RegisterLocalRequest) (*RegisterLocalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterLocal not implemented")
}
func (UnimplementedLocalControlServiceServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedLocalControlServiceServer) ListLocal(context.Context, *ListLocalRequest) (*ListLocalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListLocal not implemented")
}
func (UnimplementedLocalControlServiceServer) GetJobResult(context.Context, *GetJobResultRequest) (*GetJobResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetJobResult not implemented")
}
func (UnimplementedLocalControlServiceServer) mustEmbedUnimplementedLocalControlServiceServer() {}
func (UnimplementedLocalControlServiceServer) testEmbeddedByValue()                             {}

// UnsafeLocalControlServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LocalControlServiceServer will
// result in compilation errors.
type UnsafeLocalControlServiceServer interface {
	mustEmbedUnimplementedLocalControlServiceServer()
}

func RegisterLocalControlServiceServer(s grpc.ServiceRegistrar, srv LocalControlServiceServer) {
	// If the following call pancis, it indicates UnimplementedLocalControlServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LocalControlService_ServiceDesc, srv)
}

func _LocalControlService_RegisterLocal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterLocalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocalControlServiceServer).RegisterLocal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LocalControlService_RegisterLocal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocalControlServiceServer).RegisterLocal(ctx, req.(*RegisterLocalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocalControlService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocalControlServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LocalControlService_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocalControlServiceServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocalControlService_ListLocal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLocalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocalControlServiceServer).ListLocal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LocalControlService_ListLocal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocalControlServiceServer).ListLocal(ctx, req.(*ListLocalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocalControlService_GetJobResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJobResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocalControlServiceServer).GetJobResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LocalControlService_GetJobResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocalControlServiceServer).GetJobResult(ctx, req.(*GetJobResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LocalControlService_ServiceDesc is the grpc.ServiceDesc for LocalControlService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LocalControlService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "croupier.agent.local.v1.LocalControlService",
	HandlerType: (*LocalControlServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterLocal",
			Handler:    _LocalControlService_RegisterLocal_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _LocalControlService_Heartbeat_Handler,
		},
		{
			MethodName: "ListLocal",
			Handler:    _LocalControlService_ListLocal_Handler,
		},
		{
			MethodName: "GetJobResult",
			Handler:    _LocalControlService_GetJobResult_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "croupier/agent/local/v1/local.proto",
}
