// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.0
// 	protoc        (unknown)
// source: croupier/common/v1/ui.proto

package commonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Generic i18n text with common languages.
type I18NText struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	En            string                 `protobuf:"bytes,1,opt,name=en,proto3" json:"en,omitempty"`
	Zh            string                 `protobuf:"bytes,2,opt,name=zh,proto3" json:"zh,omitempty"` // reserved for more locales
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *I18NText) Reset() {
	*x = I18NText{}
	mi := &file_croupier_common_v1_ui_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *I18NText) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*I18NText) ProtoMessage() {}

func (x *I18NText) ProtoReflect() protoreflect.Message {
	mi := &file_croupier_common_v1_ui_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use I18NText.ProtoReflect.Descriptor instead.
func (*I18NText) Descriptor() ([]byte, []int) {
	return file_croupier_common_v1_ui_proto_rawDescGZIP(), []int{0}
}

func (x *I18NText) GetEn() string {
	if x != nil {
		return x.En
	}
	return ""
}

func (x *I18NText) GetZh() string {
	if x != nil {
		return x.Zh
	}
	return ""
}

// Menu metadata for building dynamic navigation in the UI.
type Menu struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Section       string                 `protobuf:"bytes,1,opt,name=section,proto3" json:"section,omitempty"` // Top-level section: e.g. "Function Management" | "Operations" | "Analytics"
	Group         string                 `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`     // Group within section: e.g. "Moderation" | "Player"
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`       // Preferred landing path: e.g. "/functions/invoke"
	Order         int32                  `protobuf:"varint,4,opt,name=order,proto3" json:"order,omitempty"`    // Ordering weight (ascending)
	Icon          string                 `protobuf:"bytes,5,opt,name=icon,proto3" json:"icon,omitempty"`       // Icon id (frontend mapping)
	Badge         string                 `protobuf:"bytes,6,opt,name=badge,proto3" json:"badge,omitempty"`     // "beta" | "new" | custom
	Hidden        bool                   `protobuf:"varint,7,opt,name=hidden,proto3" json:"hidden,omitempty"`  // true → do not show in menu
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Menu) Reset() {
	*x = Menu{}
	mi := &file_croupier_common_v1_ui_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Menu) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Menu) ProtoMessage() {}

func (x *Menu) ProtoReflect() protoreflect.Message {
	mi := &file_croupier_common_v1_ui_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Menu.ProtoReflect.Descriptor instead.
func (*Menu) Descriptor() ([]byte, []int) {
	return file_croupier_common_v1_ui_proto_rawDescGZIP(), []int{1}
}

func (x *Menu) GetSection() string {
	if x != nil {
		return x.Section
	}
	return ""
}

func (x *Menu) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *Menu) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Menu) GetOrder() int32 {
	if x != nil {
		return x.Order
	}
	return 0
}

func (x *Menu) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *Menu) GetBadge() string {
	if x != nil {
		return x.Badge
	}
	return ""
}

func (x *Menu) GetHidden() bool {
	if x != nil {
		return x.Hidden
	}
	return false
}

// Role binding: which roles should be granted which verbs by default.
type RoleBinding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Verbs         []string               `protobuf:"bytes,2,rep,name=verbs,proto3" json:"verbs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleBinding) Reset() {
	*x = RoleBinding{}
	mi := &file_croupier_common_v1_ui_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleBinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleBinding) ProtoMessage() {}

func (x *RoleBinding) ProtoReflect() protoreflect.Message {
	mi := &file_croupier_common_v1_ui_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleBinding.ProtoReflect.Descriptor instead.
func (*RoleBinding) Descriptor() ([]byte, []int) {
	return file_croupier_common_v1_ui_proto_rawDescGZIP(), []int{2}
}

func (x *RoleBinding) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *RoleBinding) GetVerbs() []string {
	if x != nil {
		return x.Verbs
	}
	return nil
}

// Permission specification for a resource (function/component).
type PermissionSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Verbs applicable to the resource: e.g. read/invoke/view_history/manage/use
	Verbs []string `protobuf:"bytes,1,rep,name=verbs,proto3" json:"verbs,omitempty"`
	// Scopes supported for ABAC policies: e.g. game/env/function_id
	Scopes []string `protobuf:"bytes,2,rep,name=scopes,proto3" json:"scopes,omitempty"`
	// Default role → verbs bindings (suggested grants).
	Defaults []*RoleBinding `protobuf:"bytes,3,rep,name=defaults,proto3" json:"defaults,omitempty"`
	// Optional zh texts per verb. If absent, UI will fallback to templates.
	I18NZh        map[string]string `protobuf:"bytes,4,rep,name=i18n_zh,json=i18nZh,proto3" json:"i18n_zh,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermissionSpec) Reset() {
	*x = PermissionSpec{}
	mi := &file_croupier_common_v1_ui_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermissionSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionSpec) ProtoMessage() {}

func (x *PermissionSpec) ProtoReflect() protoreflect.Message {
	mi := &file_croupier_common_v1_ui_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionSpec.ProtoReflect.Descriptor instead.
func (*PermissionSpec) Descriptor() ([]byte, []int) {
	return file_croupier_common_v1_ui_proto_rawDescGZIP(), []int{3}
}

func (x *PermissionSpec) GetVerbs() []string {
	if x != nil {
		return x.Verbs
	}
	return nil
}

func (x *PermissionSpec) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

func (x *PermissionSpec) GetDefaults() []*RoleBinding {
	if x != nil {
		return x.Defaults
	}
	return nil
}

func (x *PermissionSpec) GetI18NZh() map[string]string {
	if x != nil {
		return x.I18NZh
	}
	return nil
}

var File_croupier_common_v1_ui_proto protoreflect.FileDescriptor

var file_croupier_common_v1_ui_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x63, 0x72, 0x6f, 0x75, 0x70, 0x69, 0x65, 0x72, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x75, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x63,
	0x72, 0x6f, 0x75, 0x70, 0x69, 0x65, 0x72, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x76,
	0x31, 0x22, 0x2a, 0x0a, 0x08, 0x49, 0x31, 0x38, 0x6e, 0x54, 0x65, 0x78, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x65, 0x6e, 0x12, 0x0e, 0x0a,
	0x02, 0x7a, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x7a, 0x68, 0x22, 0xa2, 0x01,
	0x0a, 0x04, 0x4d, 0x65, 0x6e, 0x75, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x14, 0x0a, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x72,
	0x64, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x12, 0x12, 0x0a, 0x04, 0x69, 0x63, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x69, 0x63, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x61, 0x64, 0x67, 0x65, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x62, 0x61, 0x64, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x69,
	0x64, 0x64, 0x65, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x68, 0x69, 0x64, 0x64,
	0x65, 0x6e, 0x22, 0x37, 0x0a, 0x0b, 0x52, 0x6f, 0x6c, 0x65, 0x42, 0x69, 0x6e, 0x64, 0x69, 0x6e,
	0x67, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x72, 0x6f, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x65, 0x72, 0x62, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x76, 0x65, 0x72, 0x62, 0x73, 0x22, 0xff, 0x01, 0x0a, 0x0e,
	0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x53, 0x70, 0x65, 0x63, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x65, 0x72, 0x62, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x76,
	0x65, 0x72, 0x62, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x63, 0x6f, 0x70, 0x65, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x73, 0x63, 0x6f, 0x70, 0x65, 0x73, 0x12, 0x3b, 0x0a, 0x08,
	0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f,
	0x2e, 0x63, 0x72, 0x6f, 0x75, 0x70, 0x69, 0x65, 0x72, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2e, 0x76, 0x31, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x42, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x52,
	0x08, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x73, 0x12, 0x47, 0x0a, 0x07, 0x69, 0x31, 0x38,
	0x6e, 0x5f, 0x7a, 0x68, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x63, 0x72, 0x6f,
	0x75, 0x70, 0x69, 0x65, 0x72, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e,
	0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x53, 0x70, 0x65, 0x63, 0x2e, 0x49,
	0x31, 0x38, 0x6e, 0x5a, 0x68, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x69, 0x31, 0x38, 0x6e,
	0x5a, 0x68, 0x1a, 0x39, 0x0a, 0x0b, 0x49, 0x31, 0x38, 0x6e, 0x5a, 0x68, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x42, 0x6a, 0x0a,
	0x25, 0x69, 0x6f, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x75, 0x69, 0x68, 0x61,
	0x69, 0x72, 0x75, 0x2e, 0x63, 0x72, 0x6f, 0x75, 0x70, 0x69, 0x65, 0x72, 0x2e, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x50, 0x01, 0x5a, 0x3f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x75, 0x69, 0x68, 0x61, 0x69, 0x72, 0x75, 0x2f, 0x63, 0x72,
	0x6f, 0x75, 0x70, 0x69, 0x65, 0x72, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x2f, 0x63, 0x72,
	0x6f, 0x75, 0x70, 0x69, 0x65, 0x72, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x76, 0x31,
	0x3b, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_croupier_common_v1_ui_proto_rawDescOnce sync.Once
	file_croupier_common_v1_ui_proto_rawDescData = file_croupier_common_v1_ui_proto_rawDesc
)

func file_croupier_common_v1_ui_proto_rawDescGZIP() []byte {
	file_croupier_common_v1_ui_proto_rawDescOnce.Do(func() {
		file_croupier_common_v1_ui_proto_rawDescData = protoimpl.X.CompressGZIP(file_croupier_common_v1_ui_proto_rawDescData)
	})
	return file_croupier_common_v1_ui_proto_rawDescData
}

var file_croupier_common_v1_ui_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_croupier_common_v1_ui_proto_goTypes = []any{
	(*I18NText)(nil),       // 0: croupier.common.v1.I18nText
	(*Menu)(nil),           // 1: croupier.common.v1.Menu
	(*RoleBinding)(nil),    // 2: croupier.common.v1.RoleBinding
	(*PermissionSpec)(nil), // 3: croupier.common.v1.PermissionSpec
	nil,                    // 4: croupier.common.v1.PermissionSpec.I18nZhEntry
}
var file_croupier_common_v1_ui_proto_depIdxs = []int32{
	2, // 0: croupier.common.v1.PermissionSpec.defaults:type_name -> croupier.common.v1.RoleBinding
	4, // 1: croupier.common.v1.PermissionSpec.i18n_zh:type_name -> croupier.common.v1.PermissionSpec.I18nZhEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_croupier_common_v1_ui_proto_init() }
func file_croupier_common_v1_ui_proto_init() {
	if File_croupier_common_v1_ui_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_croupier_common_v1_ui_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_croupier_common_v1_ui_proto_goTypes,
		DependencyIndexes: file_croupier_common_v1_ui_proto_depIdxs,
		MessageInfos:      file_croupier_common_v1_ui_proto_msgTypes,
	}.Build()
	File_croupier_common_v1_ui_proto = out.File
	file_croupier_common_v1_ui_proto_rawDesc = nil
	file_croupier_common_v1_ui_proto_goTypes = nil
	file_croupier_common_v1_ui_proto_depIdxs = nil
}
