// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: croupier/common/v1/ui.proto

package commonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Generic i18n text with common languages.
type I18NText struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	En            string                 `protobuf:"bytes,1,opt,name=en,proto3" json:"en,omitempty"`
	Zh            string                 `protobuf:"bytes,2,opt,name=zh,proto3" json:"zh,omitempty"` // reserved for more locales
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *I18NText) Reset() {
	*x = I18NText{}
	mi := &file_croupier_common_v1_ui_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *I18NText) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*I18NText) ProtoMessage() {}

func (x *I18NText) ProtoReflect() protoreflect.Message {
	mi := &file_croupier_common_v1_ui_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use I18NText.ProtoReflect.Descriptor instead.
func (*I18NText) Descriptor() ([]byte, []int) {
	return file_croupier_common_v1_ui_proto_rawDescGZIP(), []int{0}
}

func (x *I18NText) GetEn() string {
	if x != nil {
		return x.En
	}
	return ""
}

func (x *I18NText) GetZh() string {
	if x != nil {
		return x.Zh
	}
	return ""
}

// Menu metadata for building dynamic navigation in the UI.
type Menu struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Section       string                 `protobuf:"bytes,1,opt,name=section,proto3" json:"section,omitempty"` // Top-level section: e.g. "Function Management" | "Operations" | "Analytics"
	Group         string                 `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`     // Group within section: e.g. "Moderation" | "Player"
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`       // Preferred landing path: e.g. "/functions/invoke"
	Order         int32                  `protobuf:"varint,4,opt,name=order,proto3" json:"order,omitempty"`    // Ordering weight (ascending)
	Icon          string                 `protobuf:"bytes,5,opt,name=icon,proto3" json:"icon,omitempty"`       // Icon id (frontend mapping)
	Badge         string                 `protobuf:"bytes,6,opt,name=badge,proto3" json:"badge,omitempty"`     // "beta" | "new" | custom
	Hidden        bool                   `protobuf:"varint,7,opt,name=hidden,proto3" json:"hidden,omitempty"`  // true → do not show in menu
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Menu) Reset() {
	*x = Menu{}
	mi := &file_croupier_common_v1_ui_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Menu) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Menu) ProtoMessage() {}

func (x *Menu) ProtoReflect() protoreflect.Message {
	mi := &file_croupier_common_v1_ui_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Menu.ProtoReflect.Descriptor instead.
func (*Menu) Descriptor() ([]byte, []int) {
	return file_croupier_common_v1_ui_proto_rawDescGZIP(), []int{1}
}

func (x *Menu) GetSection() string {
	if x != nil {
		return x.Section
	}
	return ""
}

func (x *Menu) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *Menu) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Menu) GetOrder() int32 {
	if x != nil {
		return x.Order
	}
	return 0
}

func (x *Menu) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *Menu) GetBadge() string {
	if x != nil {
		return x.Badge
	}
	return ""
}

func (x *Menu) GetHidden() bool {
	if x != nil {
		return x.Hidden
	}
	return false
}

// Role binding: which roles should be granted which verbs by default.
type RoleBinding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Verbs         []string               `protobuf:"bytes,2,rep,name=verbs,proto3" json:"verbs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleBinding) Reset() {
	*x = RoleBinding{}
	mi := &file_croupier_common_v1_ui_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleBinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleBinding) ProtoMessage() {}

func (x *RoleBinding) ProtoReflect() protoreflect.Message {
	mi := &file_croupier_common_v1_ui_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleBinding.ProtoReflect.Descriptor instead.
func (*RoleBinding) Descriptor() ([]byte, []int) {
	return file_croupier_common_v1_ui_proto_rawDescGZIP(), []int{2}
}

func (x *RoleBinding) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *RoleBinding) GetVerbs() []string {
	if x != nil {
		return x.Verbs
	}
	return nil
}

// Permission specification for a resource (function/component).
type PermissionSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Verbs applicable to the resource: e.g. read/invoke/view_history/manage/use
	Verbs []string `protobuf:"bytes,1,rep,name=verbs,proto3" json:"verbs,omitempty"`
	// Scopes supported for ABAC policies: e.g. game/env/function_id
	Scopes []string `protobuf:"bytes,2,rep,name=scopes,proto3" json:"scopes,omitempty"`
	// Default role → verbs bindings (suggested grants).
	Defaults []*RoleBinding `protobuf:"bytes,3,rep,name=defaults,proto3" json:"defaults,omitempty"`
	// Optional zh texts per verb. If absent, UI will fallback to templates.
	I18NZh        map[string]string `protobuf:"bytes,4,rep,name=i18n_zh,json=i18nZh,proto3" json:"i18n_zh,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermissionSpec) Reset() {
	*x = PermissionSpec{}
	mi := &file_croupier_common_v1_ui_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermissionSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionSpec) ProtoMessage() {}

func (x *PermissionSpec) ProtoReflect() protoreflect.Message {
	mi := &file_croupier_common_v1_ui_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionSpec.ProtoReflect.Descriptor instead.
func (*PermissionSpec) Descriptor() ([]byte, []int) {
	return file_croupier_common_v1_ui_proto_rawDescGZIP(), []int{3}
}

func (x *PermissionSpec) GetVerbs() []string {
	if x != nil {
		return x.Verbs
	}
	return nil
}

func (x *PermissionSpec) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

func (x *PermissionSpec) GetDefaults() []*RoleBinding {
	if x != nil {
		return x.Defaults
	}
	return nil
}

func (x *PermissionSpec) GetI18NZh() map[string]string {
	if x != nil {
		return x.I18NZh
	}
	return nil
}

// XRender widget configuration for a field.
type XRenderWidget struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Widget        string                 `protobuf:"bytes,1,opt,name=widget,proto3" json:"widget,omitempty"`                                                                         // Widget type: input/textarea/number/select/checkbox/radio/switch/date/time/json-editor/file
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`                                                                           // Display label (supports i18n key)
	Placeholder   string                 `protobuf:"bytes,3,opt,name=placeholder,proto3" json:"placeholder,omitempty"`                                                               // Placeholder text
	Disabled      bool                   `protobuf:"varint,4,opt,name=disabled,proto3" json:"disabled,omitempty"`                                                                    // Whether the field is disabled
	ReadOnly      bool                   `protobuf:"varint,5,opt,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`                                                    // Whether the field is read-only
	Hidden        bool                   `protobuf:"varint,6,opt,name=hidden,proto3" json:"hidden,omitempty"`                                                                        // Whether the field is hidden
	Span          int32                  `protobuf:"varint,7,opt,name=span,proto3" json:"span,omitempty"`                                                                            // Grid span (1-24)
	Props         map[string]string      `protobuf:"bytes,8,rep,name=props,proto3" json:"props,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Additional widget properties
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *XRenderWidget) Reset() {
	*x = XRenderWidget{}
	mi := &file_croupier_common_v1_ui_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *XRenderWidget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XRenderWidget) ProtoMessage() {}

func (x *XRenderWidget) ProtoReflect() protoreflect.Message {
	mi := &file_croupier_common_v1_ui_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XRenderWidget.ProtoReflect.Descriptor instead.
func (*XRenderWidget) Descriptor() ([]byte, []int) {
	return file_croupier_common_v1_ui_proto_rawDescGZIP(), []int{4}
}

func (x *XRenderWidget) GetWidget() string {
	if x != nil {
		return x.Widget
	}
	return ""
}

func (x *XRenderWidget) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *XRenderWidget) GetPlaceholder() string {
	if x != nil {
		return x.Placeholder
	}
	return ""
}

func (x *XRenderWidget) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

func (x *XRenderWidget) GetReadOnly() bool {
	if x != nil {
		return x.ReadOnly
	}
	return false
}

func (x *XRenderWidget) GetHidden() bool {
	if x != nil {
		return x.Hidden
	}
	return false
}

func (x *XRenderWidget) GetSpan() int32 {
	if x != nil {
		return x.Span
	}
	return 0
}

func (x *XRenderWidget) GetProps() map[string]string {
	if x != nil {
		return x.Props
	}
	return nil
}

// XRender form configuration.
type XRenderFormConfig struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	LayoutType    string                    `protobuf:"bytes,1,opt,name=layout_type,json=layoutType,proto3" json:"layout_type,omitempty"`                                                   // Layout: default/inline/flex
	Column        int32                     `protobuf:"varint,2,opt,name=column,proto3" json:"column,omitempty"`                                                                            // Column count for grid layout
	LabelAlign    string                    `protobuf:"bytes,3,opt,name=label_align,json=labelAlign,proto3" json:"label_align,omitempty"`                                                   // Label alignment: left/right/top
	LabelWidth    int32                     `protobuf:"varint,4,opt,name=label_width,json=labelWidth,proto3" json:"label_width,omitempty"`                                                  // Label width in pixels
	Colon         bool                      `protobuf:"varint,5,opt,name=colon,proto3" json:"colon,omitempty"`                                                                              // Show colon after label
	Widgets       map[string]*XRenderWidget `protobuf:"bytes,6,rep,name=widgets,proto3" json:"widgets,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Field-specific widget configs (key: field path)
	DisplayOrder  []string                  `protobuf:"bytes,7,rep,name=display_order,json=displayOrder,proto3" json:"display_order,omitempty"`                                             // Field display order
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *XRenderFormConfig) Reset() {
	*x = XRenderFormConfig{}
	mi := &file_croupier_common_v1_ui_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *XRenderFormConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XRenderFormConfig) ProtoMessage() {}

func (x *XRenderFormConfig) ProtoReflect() protoreflect.Message {
	mi := &file_croupier_common_v1_ui_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XRenderFormConfig.ProtoReflect.Descriptor instead.
func (*XRenderFormConfig) Descriptor() ([]byte, []int) {
	return file_croupier_common_v1_ui_proto_rawDescGZIP(), []int{5}
}

func (x *XRenderFormConfig) GetLayoutType() string {
	if x != nil {
		return x.LayoutType
	}
	return ""
}

func (x *XRenderFormConfig) GetColumn() int32 {
	if x != nil {
		return x.Column
	}
	return 0
}

func (x *XRenderFormConfig) GetLabelAlign() string {
	if x != nil {
		return x.LabelAlign
	}
	return ""
}

func (x *XRenderFormConfig) GetLabelWidth() int32 {
	if x != nil {
		return x.LabelWidth
	}
	return 0
}

func (x *XRenderFormConfig) GetColon() bool {
	if x != nil {
		return x.Colon
	}
	return false
}

func (x *XRenderFormConfig) GetWidgets() map[string]*XRenderWidget {
	if x != nil {
		return x.Widgets
	}
	return nil
}

func (x *XRenderFormConfig) GetDisplayOrder() []string {
	if x != nil {
		return x.DisplayOrder
	}
	return nil
}

// Route-specific display configuration for functions.
type RouteDisplayConfig struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RoutePattern     string                 `protobuf:"bytes,1,opt,name=route_pattern,json=routePattern,proto3" json:"route_pattern,omitempty"`               // Route pattern (e.g., "/functions/*", "/quick-actions")
	FormConfig       *XRenderFormConfig     `protobuf:"bytes,2,opt,name=form_config,json=formConfig,proto3" json:"form_config,omitempty"`                     // Form configuration for this route
	HiddenFields     []string               `protobuf:"bytes,3,rep,name=hidden_fields,json=hiddenFields,proto3" json:"hidden_fields,omitempty"`               // Fields to hide in this route
	RequiredFields   []string               `protobuf:"bytes,4,rep,name=required_fields,json=requiredFields,proto3" json:"required_fields,omitempty"`         // Fields required in this route
	SubmitButtonText string                 `protobuf:"bytes,5,opt,name=submit_button_text,json=submitButtonText,proto3" json:"submit_button_text,omitempty"` // Custom submit button text
	CompactMode      bool                   `protobuf:"varint,6,opt,name=compact_mode,json=compactMode,proto3" json:"compact_mode,omitempty"`                 // Use compact display mode
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RouteDisplayConfig) Reset() {
	*x = RouteDisplayConfig{}
	mi := &file_croupier_common_v1_ui_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteDisplayConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteDisplayConfig) ProtoMessage() {}

func (x *RouteDisplayConfig) ProtoReflect() protoreflect.Message {
	mi := &file_croupier_common_v1_ui_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteDisplayConfig.ProtoReflect.Descriptor instead.
func (*RouteDisplayConfig) Descriptor() ([]byte, []int) {
	return file_croupier_common_v1_ui_proto_rawDescGZIP(), []int{6}
}

func (x *RouteDisplayConfig) GetRoutePattern() string {
	if x != nil {
		return x.RoutePattern
	}
	return ""
}

func (x *RouteDisplayConfig) GetFormConfig() *XRenderFormConfig {
	if x != nil {
		return x.FormConfig
	}
	return nil
}

func (x *RouteDisplayConfig) GetHiddenFields() []string {
	if x != nil {
		return x.HiddenFields
	}
	return nil
}

func (x *RouteDisplayConfig) GetRequiredFields() []string {
	if x != nil {
		return x.RequiredFields
	}
	return nil
}

func (x *RouteDisplayConfig) GetSubmitButtonText() string {
	if x != nil {
		return x.SubmitButtonText
	}
	return ""
}

func (x *RouteDisplayConfig) GetCompactMode() bool {
	if x != nil {
		return x.CompactMode
	}
	return false
}

var File_croupier_common_v1_ui_proto protoreflect.FileDescriptor

const file_croupier_common_v1_ui_proto_rawDesc = "" +
	"\n" +
	"\x1bcroupier/common/v1/ui.proto\x12\x12croupier.common.v1\"*\n" +
	"\bI18nText\x12\x0e\n" +
	"\x02en\x18\x01 \x01(\tR\x02en\x12\x0e\n" +
	"\x02zh\x18\x02 \x01(\tR\x02zh\"\xa2\x01\n" +
	"\x04Menu\x12\x18\n" +
	"\asection\x18\x01 \x01(\tR\asection\x12\x14\n" +
	"\x05group\x18\x02 \x01(\tR\x05group\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x14\n" +
	"\x05order\x18\x04 \x01(\x05R\x05order\x12\x12\n" +
	"\x04icon\x18\x05 \x01(\tR\x04icon\x12\x14\n" +
	"\x05badge\x18\x06 \x01(\tR\x05badge\x12\x16\n" +
	"\x06hidden\x18\a \x01(\bR\x06hidden\"7\n" +
	"\vRoleBinding\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x14\n" +
	"\x05verbs\x18\x02 \x03(\tR\x05verbs\"\xff\x01\n" +
	"\x0ePermissionSpec\x12\x14\n" +
	"\x05verbs\x18\x01 \x03(\tR\x05verbs\x12\x16\n" +
	"\x06scopes\x18\x02 \x03(\tR\x06scopes\x12;\n" +
	"\bdefaults\x18\x03 \x03(\v2\x1f.croupier.common.v1.RoleBindingR\bdefaults\x12G\n" +
	"\ai18n_zh\x18\x04 \x03(\v2..croupier.common.v1.PermissionSpec.I18nZhEntryR\x06i18nZh\x1a9\n" +
	"\vI18nZhEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc2\x02\n" +
	"\rXRenderWidget\x12\x16\n" +
	"\x06widget\x18\x01 \x01(\tR\x06widget\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12 \n" +
	"\vplaceholder\x18\x03 \x01(\tR\vplaceholder\x12\x1a\n" +
	"\bdisabled\x18\x04 \x01(\bR\bdisabled\x12\x1b\n" +
	"\tread_only\x18\x05 \x01(\bR\breadOnly\x12\x16\n" +
	"\x06hidden\x18\x06 \x01(\bR\x06hidden\x12\x12\n" +
	"\x04span\x18\a \x01(\x05R\x04span\x12B\n" +
	"\x05props\x18\b \x03(\v2,.croupier.common.v1.XRenderWidget.PropsEntryR\x05props\x1a8\n" +
	"\n" +
	"PropsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf6\x02\n" +
	"\x11XRenderFormConfig\x12\x1f\n" +
	"\vlayout_type\x18\x01 \x01(\tR\n" +
	"layoutType\x12\x16\n" +
	"\x06column\x18\x02 \x01(\x05R\x06column\x12\x1f\n" +
	"\vlabel_align\x18\x03 \x01(\tR\n" +
	"labelAlign\x12\x1f\n" +
	"\vlabel_width\x18\x04 \x01(\x05R\n" +
	"labelWidth\x12\x14\n" +
	"\x05colon\x18\x05 \x01(\bR\x05colon\x12L\n" +
	"\awidgets\x18\x06 \x03(\v22.croupier.common.v1.XRenderFormConfig.WidgetsEntryR\awidgets\x12#\n" +
	"\rdisplay_order\x18\a \x03(\tR\fdisplayOrder\x1a]\n" +
	"\fWidgetsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x127\n" +
	"\x05value\x18\x02 \x01(\v2!.croupier.common.v1.XRenderWidgetR\x05value:\x028\x01\"\xa0\x02\n" +
	"\x12RouteDisplayConfig\x12#\n" +
	"\rroute_pattern\x18\x01 \x01(\tR\froutePattern\x12F\n" +
	"\vform_config\x18\x02 \x01(\v2%.croupier.common.v1.XRenderFormConfigR\n" +
	"formConfig\x12#\n" +
	"\rhidden_fields\x18\x03 \x03(\tR\fhiddenFields\x12'\n" +
	"\x0frequired_fields\x18\x04 \x03(\tR\x0erequiredFields\x12,\n" +
	"\x12submit_button_text\x18\x05 \x01(\tR\x10submitButtonText\x12!\n" +
	"\fcompact_mode\x18\x06 \x01(\bR\vcompactModeBj\n" +
	"%io.github.cuihairu.croupier.common.v1P\x01Z?github.com/cuihairu/croupier/pkg/pb/croupier/common/v1;commonv1b\x06proto3"

var (
	file_croupier_common_v1_ui_proto_rawDescOnce sync.Once
	file_croupier_common_v1_ui_proto_rawDescData []byte
)

func file_croupier_common_v1_ui_proto_rawDescGZIP() []byte {
	file_croupier_common_v1_ui_proto_rawDescOnce.Do(func() {
		file_croupier_common_v1_ui_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_croupier_common_v1_ui_proto_rawDesc), len(file_croupier_common_v1_ui_proto_rawDesc)))
	})
	return file_croupier_common_v1_ui_proto_rawDescData
}

var file_croupier_common_v1_ui_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_croupier_common_v1_ui_proto_goTypes = []any{
	(*I18NText)(nil),           // 0: croupier.common.v1.I18nText
	(*Menu)(nil),               // 1: croupier.common.v1.Menu
	(*RoleBinding)(nil),        // 2: croupier.common.v1.RoleBinding
	(*PermissionSpec)(nil),     // 3: croupier.common.v1.PermissionSpec
	(*XRenderWidget)(nil),      // 4: croupier.common.v1.XRenderWidget
	(*XRenderFormConfig)(nil),  // 5: croupier.common.v1.XRenderFormConfig
	(*RouteDisplayConfig)(nil), // 6: croupier.common.v1.RouteDisplayConfig
	nil,                        // 7: croupier.common.v1.PermissionSpec.I18nZhEntry
	nil,                        // 8: croupier.common.v1.XRenderWidget.PropsEntry
	nil,                        // 9: croupier.common.v1.XRenderFormConfig.WidgetsEntry
}
var file_croupier_common_v1_ui_proto_depIdxs = []int32{
	2, // 0: croupier.common.v1.PermissionSpec.defaults:type_name -> croupier.common.v1.RoleBinding
	7, // 1: croupier.common.v1.PermissionSpec.i18n_zh:type_name -> croupier.common.v1.PermissionSpec.I18nZhEntry
	8, // 2: croupier.common.v1.XRenderWidget.props:type_name -> croupier.common.v1.XRenderWidget.PropsEntry
	9, // 3: croupier.common.v1.XRenderFormConfig.widgets:type_name -> croupier.common.v1.XRenderFormConfig.WidgetsEntry
	5, // 4: croupier.common.v1.RouteDisplayConfig.form_config:type_name -> croupier.common.v1.XRenderFormConfig
	4, // 5: croupier.common.v1.XRenderFormConfig.WidgetsEntry.value:type_name -> croupier.common.v1.XRenderWidget
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_croupier_common_v1_ui_proto_init() }
func file_croupier_common_v1_ui_proto_init() {
	if File_croupier_common_v1_ui_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_croupier_common_v1_ui_proto_rawDesc), len(file_croupier_common_v1_ui_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_croupier_common_v1_ui_proto_goTypes,
		DependencyIndexes: file_croupier_common_v1_ui_proto_depIdxs,
		MessageInfos:      file_croupier_common_v1_ui_proto_msgTypes,
	}.Build()
	File_croupier_common_v1_ui_proto = out.File
	file_croupier_common_v1_ui_proto_goTypes = nil
	file_croupier_common_v1_ui_proto_depIdxs = nil
}
